"""Output layer for the under-15 stream engine: JSON payload + standalone HTML.

Deliberately does not import jyotish/output.py's ExplainabilityEngine (built
around 199 field cards, route-suitability badges, etc.) -- this report is
much simpler by design: 3 streams, each with its ranked subject list.
"""
from __future__ import annotations

import html
import json
import os
from datetime import datetime
from typing import Any, Dict

from jyotish.validation_contract import UNIVERSAL_DISCLAIMER
from .subject_registry import STREAM_META
from .field_derived_stream import FIELD_DERIVED_EVIDENCE_CAP

# 2026-07-24: bumped v4->v5 -- CRITICAL bug #1 fix (see
# md/STREAM_DETERMINATION_CRITICAL_FIXES_20260724.md): surfaced
# numeric_rank/d1_candidate_rank/precedence_decision/recommended_stream
# explicitly, and added recommendation_basis_note so a reader can no longer
# be misled when recommended_stream != the highest normalized_score stream.
REPORT_CONTRACT_VERSION = "stream-determination-report.v5"


def build_report_payload(
    payload: Any, determination: Dict[str, Any], *,
    forced_override: bool = False, eligibility_status: str = "NORMAL",
    cross_validation: Dict[str, Any] | None = None,
    stream_narrative: Dict[str, Any] | None = None,
) -> Dict[str, Any]:
    """Wrap the raw scoring output with chart identity + disclaimer for JSON export.

    GAP-FIX (2026-07-22, audit gap 25): `forced_override`/`eligibility_status`
    make it explicit when a report was generated with force=True on a chart
    whose current_age is >= 15 (valid for regression testing, but the report
    must say so rather than silently presenting a test run as a normal
    "Strongest Match" recommendation for a child).
    """
    # GAP-FIX (2026-07-22, audit): stamp the same source_sha256/chart_path
    # jyotish/engine_io.py already computes at parse time (payload.
    # source_identity) into every stream report. Without this, two reports
    # for a same-named chart file generated at different times had no way
    # to prove whether they were scored against the same underlying chart
    # data -- confirmed live during this audit: a chart's own on-disk
    # shadbala_virupas values had drifted between two report-generation
    # runs, and nothing in the report could reveal that.
    source_identity = getattr(payload, "source_identity", {}) or {}
    return {
        "contract_version": REPORT_CONTRACT_VERSION,
        "engine_version": determination.get("engine_version"),
        "calculation_profile": determination.get("calculation_profile", "UNKNOWN"),
        "scoring_contract_version": determination.get("scoring_contract_version"),
        "engine_build_fingerprint": determination.get("engine_build_fingerprint", {}),
        "calculation_identity": determination.get("calculation_identity", {}),
        "input_quality": determination.get("input_quality", {}),
        "calibration": determination.get("calibration", {}),
        "forced_override": forced_override,
        "eligibility_status": eligibility_status,
        "name": getattr(payload, "name", "") or "Unknown",
        "current_age": getattr(payload, "current_age", None),
        "dob": getattr(payload, "dob", ""),
        "source_identity": {
            "source_sha256": source_identity.get("source_sha256", "NOT_AVAILABLE"),
            "chart_path": source_identity.get("chart_path", "NOT_SUPPLIED"),
            "note": (
                "Hash of the raw chart JSON this report was scored against. "
                "Two reports for a same-named chart file are only guaranteed "
                "to reflect identical underlying data if this hash matches."
            ),
        },
        "eligibility_note": (
            "Generated by the early-age (<15) Stream Determination engine, not "
            "the main Field Determination engine. Recommends broad Science / "
            "Commerce / Humanities direction and subject choices only -- not "
            "specific vocational branches, which are only meaningful once a "
            "stream and subject combination has actually been chosen."
        ),
        "dominant_stream": determination.get("dominant_stream"),
        "top_ranked_stream": determination.get("top_ranked_stream"),
        # GAP-FIX (2026-07-24, CRITICAL bug #1): see stream_scoring.py's
        # SCORING_CONTRACT_VERSION v7 note. numeric_rank/d1_candidate_rank/
        # precedence_decision/recommended_stream are now separate, named
        # fields instead of being implied by streams[] list order.
        "numeric_rank": determination.get("numeric_rank", []),
        "d1_candidate_rank": determination.get("d1_candidate_rank", []),
        "precedence_decision": determination.get("precedence_decision"),
        "recommended_stream": determination.get("recommended_stream"),
        # A reader who only glances at "recommended_stream" and the streams[]
        # score list could otherwise be misled exactly the way the
        # 2026-07-24 external review was (recommended stream shown with a
        # LOWER normalized_score than another stream) -- state explicitly
        # whenever that's the case, and always state the basis.
        "recommendation_basis_note": (
            (
                "recommended_stream ({rec}) is the classical-precedence-informed pick "
                "(see precedence_chain_resolution_stage='{stage}'), NOT the raw "
                "numeric score leader ({num}). Compare the two streams' "
                "normalized_score in streams[] / numeric_rank before treating this as "
                "a purely score-based ranking."
            ).format(
                rec=determination.get("recommended_stream"),
                stage=determination.get("precedence_chain_resolution_stage"),
                num=(determination.get("numeric_rank") or [None])[0],
            )
            if (determination.get("recommended_stream")
                and determination.get("numeric_rank")
                and determination.get("recommended_stream") != determination["numeric_rank"][0])
            else (
                "recommended_stream matches the raw numeric score leader "
                "(numeric_rank[0]) for this chart."
            )
        ),
        "recommendation_status": determination.get("recommendation_status", "UNKNOWN"),
        "evidence_completeness": determination.get("evidence_completeness", 0.0),
        "planet_strength_coverage": determination.get("planet_strength_coverage", 0.0),
        "score_gap_top_two": determination.get("score_gap_top_two", 0.0),
        "is_close_call": determination.get("is_close_call", False),
        "close_call_note": determination.get("close_call_note", ""),
        # GAP-FIX (audit, 2026-07-23): every stream bunched within the
        # near-tie margin of its neighbor, in ranked order -- lets the
        # report distinguish a genuine 2-way tie from a 3-way toss-up.
        "tied_streams": determination.get("tied_streams", []),
        # GAP-FIX (audit #66): which stream each rubric section alone would
        # pick, vs the final combined winner -- see stream_scoring.py.
        "disagreement_ledger": determination.get("disagreement_ledger", {}),
        # BUGFIX (2026-07-24, full-production D24-arbitration run): these two
        # keys are produced by compute_stream_determination() (see
        # stream_scoring.py ~L2980) but were never copied into the saved
        # report dict here, so every report silently dropped the D24/JAIMINI
        # arbitration outcome even though the policy ran and could have
        # changed top_ranked_stream. Restored so d1_arbitration_status /
        # d1_arbitration_detail are actually visible on disk.
        "d1_arbitration_status": determination.get("d1_arbitration_status"),
        "d1_arbitration_detail": determination.get("d1_arbitration_detail"),
        # GAP-FIX (2026-07-24): CLASSICAL PRECEDENCE CHAIN -- see
        # stream_scoring.py's _apply_classical_precedence_chain() and the
        # large comment block above it. Restored into the saved report the
        # same way d1_arbitration_status/_detail were (see BUGFIX note
        # directly above) so this is never silently dropped either.
        "precedence_chain_resolution_stage": determination.get("precedence_chain_resolution_stage"),
        "precedence_chain_detail": determination.get("precedence_chain_detail"),
        # GAP-FIX (2026-07-24, dasha as_of_date reproducibility): the exact
        # calendar date Stage 4 (dasha-relevance) used as "today" -- see
        # stream_scoring.py's compute_stream_determination(as_of_date=...).
        "evaluation_as_of_date": determination.get("evaluation_as_of_date"),
        # GAP-FIX (audit #45): non-None only when current_age indicates an
        # adult chart -- independent, second age check at the scoring layer
        # itself, not just the CLI's forced_override/eligibility_status.
        "age_routing_note": determination.get("age_routing_note"),
        "streams": [
            {
                "stream_id": s["stream_id"],
                "label": s["label"],
                "sub_archetype": s.get("sub_archetype", "General"),
                "description": s.get("description", ""),
                "score": s.get("score"),
                "normalized_score": s.get("normalized_score"),
                "score_rubric": s.get("score_rubric", {}),
                "score_compression": s.get("score_compression", {}),
                "role_placement_data_status": s.get("role_placement_data_status", "UNKNOWN"),
                # GAP-FIX (audit #62): cross-section NEUTRAL_NO_SIGNAL vs
                # POSITIVE_SUPPORT consistency, previously only on d24.
                "role_placement_signal_state": s.get("role_placement_signal_state", "UNKNOWN"),
                "relational_d1_signal_state": s.get("relational_d1_signal_state", "UNKNOWN"),
                "d24_confirmation_signal_state": s.get("d24_confirmation_signal_state", "UNKNOWN"),
                "trace": s.get("trace", []),
                "subjects": s.get("subjects", []),
            }
            for s in determination.get("streams", [])
        ],
        "planet_strengths": determination.get("planet_strengths", {}),
        # GAP-FIX ("include the comparison in the final report"): independent
        # cross-check against Field_Determination's own adult-engine macro
        # career cluster -- see Stream_Determination/cross_validate.py. None
        # if the caller skipped it (include_cross_validation=False).
        "cross_validation": cross_validation,
        # None unless compute_stream_determination() was called with
        # include_field_derived_evidence=True (default False -- experimental).
        "field_determination_evidence": determination.get("field_determination_evidence"),
        "stream_narrative": stream_narrative,
        # GAP-FIX (2026-07-22, audit gap 22): scores like "95.5" or "Physics
        # 89.3" visually resemble calibrated probabilities or validated
        # percentages -- they are not. State this explicitly rather than
        # letting the number format imply a precision the engine doesn't have.
        "score_interpretation_note": (
            "All scores in this report are relative internal support indices. "
            "They are outcome-calibrated probabilities only when calibration.status "
            "is VALIDATED_CALIBRATED and a passing validation report is attached; "
            "otherwise they are engineered, provisional 0-100 indices and must not "
            "be read as aptitude probabilities."
        ),
        # GAP-FIX (audit -- stream/planet mapping provenance): Science/
        # Commerce/Humanities are modern (CBSE-era) educational categories --
        # no classical Jyotish text defines these three exact streams, so
        # the mapping from graha/house significations (STREAM_META in
        # subject_registry.py) to "which of these 3 modern categories" is
        # this engine's own INTERPRETIVE synthesis of classical significator
        # doctrine, not a documented classical rule set or a surveyed expert
        # consensus. This is a genuine, permanent epistemic limitation, not
        # a bug to be fixed -- stated here explicitly rather than left
        # implicit in code comments a report reader would never see.
        "mapping_provenance_note": (
            "The Science/Commerce/Humanities stream categories themselves are modern "
            "(CBSE-era) educational constructs with no single classical Jyotish "
            "definition. This engine's planet-to-stream signature mapping (which "
            "grahas 'belong' to which stream) is an interpretive synthesis of "
            "classical significator doctrine (e.g. Mercury=analysis/commerce, "
            "Jupiter=wisdom/law, Mars=technical rigor), not a mapping drawn from a "
            "single cited classical source or validated against expert-astrologer "
            "consensus. Several planets (Mercury, Jupiter, Mars, Saturn, Venus, Moon) "
            "legitimately support more than one stream at once in classical doctrine; "
            "this engine resolves that overlap NUMERICALLY (see "
            "_planet_exclusivity/'exclusivity' values throughout this report's traces), "
            "by discounting a shared planet's contribution in proportion to how many "
            "streams claim it -- not by an astrological priority rule that decides "
            "which single stream a shared planet 'really' belongs to for this specific "
            "chart. That numerical resolution is an engineering choice, not a "
            "classical technique."
        ),
        "disclaimer": UNIVERSAL_DISCLAIMER,
        "generated_at": datetime.now().isoformat(timespec="seconds"),
    }


# GAP-FIX (audit, 2026-07-23): str(None) renders as the literal word "None"
# in HTML -- fine in JSON (null is a real, meaningful value there: e.g.
# dominant_stream is null on purpose when Stream_Determination withholds a
# pick), but confusing to a parent/student reading the rendered report.
# Route any Optional value that reaches the HTML template through this
# instead of a bare str(...) call.
def _fmt_optional(value: Any, none_label: str = "not declared") -> str:
    return none_label if value is None else str(value)


def _subject_rows_html(subjects: list[Dict[str, Any]]) -> str:
    rows = []
    for s in subjects:
        if s.get("core"):
            tag = "<span class='core-tag'>Core</span>"
        elif s.get("shared_elective"):
            tag = "<span class='elective-tag'>Elective (shared across streams)</span>"
        else:
            tag = "<span class='elective-tag'>Elective</span>"
        if s.get("mandatory_contraindication"):
            tag += " <span class='contra-tag'>Mandatory-planet capped</span>"
        rows.append(
            "<tr>"
            f"<td>{html.escape(s.get('label', ''))} {tag}</td>"
            f"<td class='score'>{s.get('score', 0):.1f}</td>"
            f"<td>{html.escape(s.get('rationale', ''))}</td>"
            "</tr>"
        )
    return "\n".join(rows)


def render_report_html(report: Dict[str, Any]) -> str:
    name = html.escape(report.get("name", "Unknown"))
    age = report.get("current_age")
    dominant = report.get("dominant_stream", "")
    top_ranked = report.get("top_ranked_stream", "")
    recommendation_status = report.get("recommendation_status", "UNKNOWN")

    narrative_html = ""
    narrative = report.get("stream_narrative") or {}
    if narrative:
        student_paragraphs = "".join(
            f"<p>{html.escape(str(paragraph))}</p>"
            for paragraph in ((narrative.get("student_narrative") or {}).get("paragraphs") or [])
        )
        astrology_paragraphs = "".join(
            f"<p>{html.escape(str(paragraph))}</p>"
            for paragraph in ((narrative.get("astrological_narrative") or {}).get("paragraphs") or [])
        )
        narrative_html = f"""
        <section class="narrative-card">
          <div class="narrative-meta">Narrative status: {html.escape(str(narrative.get('status', 'UNKNOWN')))}
            &middot; provider: {html.escape(str(narrative.get('provider', 'deterministic')))}
            &middot; decision locked: {html.escape(str(bool(narrative.get('decision_locked'))))}</div>
          <div class="narrative-grid">
            <div><h2>What this means for the student</h2>{student_paragraphs}</div>
            <div><h2>Astrological reasoning</h2>{astrology_paragraphs}</div>
          </div>
          <p class="cv-note">The narrative explains the deterministic result and cannot change scores,
             ranking, dominant stream or tie status.</p>
        </section>
        """

    forced_banner = ""
    if report.get("forced_override"):
        status = html.escape(str(report.get("eligibility_status", "")))
        note = (
            f"TEST-ONLY FORCED OVERRIDE ({status}): this chart is age {age} -- outside "
            "this engine's normal <15 scope. Shown only because force=True was passed; "
            "this is NOT a normal recommendation."
        )
        forced_banner = f'<div class="forced-override">{note}</div>'

    cross_validation_html = ""
    cv = report.get("cross_validation")
    if cv:
        if cv.get("error"):
            cross_validation_html = f"""
            <section class="cross-validation cv-unavailable">
              <h2>Cross-check vs. Field_Determination (adult engine)</h2>
              <p>Not available for this chart: {html.escape(str(cv.get('error', '')))}</p>
            </section>
            """
        else:
            # BUG FIX (2026-07-24, wrong comparison target): render BOTH
            # adult_vs_numeric_agreement (old `agree` behavior, vs. the raw
            # numeric leader) and adult_vs_recommended_agreement (vs. the
            # ACTUAL recommended_stream, which may be precedence-overridden
            # away from the numeric leader) -- see cross_validate.py's
            # module-level BUG FIX comment. `agree` alone was misleading
            # (e.g. Hemant M: numeric leader and adult evidence agreed on
            # Commerce while the actual recommendation was precedence-
            # overridden to Humanities).
            adult_vs_numeric = cv.get("adult_vs_numeric_agreement", cv.get("agree"))
            adult_vs_recommended = cv.get("adult_vs_recommended_agreement")

            def _agree_label(value):
                return "AGREE" if value is True else "DISAGREE" if value is False else "N/A (ambiguous domain)"

            def _agree_class(value):
                return "cv-agree" if value is True else "cv-disagree" if value is False else "cv-na"

            agree = adult_vs_numeric
            agree_label = _agree_label(agree)
            agree_class = _agree_class(agree)
            cross_validation_html = f"""
            <section class="cross-validation {agree_class}">
              <h2>Cross-check vs. Field_Determination (adult engine)</h2>
              <p class="cv-note">Independent supplementary check: reverse-derives which stream this
                 chart's own Field_Determination macro career cluster implies, and compares it
                 against both this report's numeric leader AND its actual (precedence-informed)
                 recommendation -- the two can legitimately differ.</p>
              <table>
                <tbody>
                  <tr><td>Field_Determination highest-confidence field</td>
                      <td>{html.escape(str(cv.get('field_determination_top_cluster_field_label', '')))}
                          (score: {html.escape(str(cv.get('field_determination_top_cluster_field_score', '')))},
                          confidence: {html.escape(str(cv.get('field_determination_top_cluster_confidence_band', '')))},
                          cluster_rank: {html.escape(str(cv.get('field_determination_top_cluster_rank', '')))},
                          domain: {html.escape(str(cv.get('field_determination_top_cluster_domain', '')))})</td></tr>
                  <tr><td>Macro career family / competency</td>
                      <td>{html.escape(str(cv.get('field_determination_macro_career_family', '')))} /
                          {html.escape(str(cv.get('field_determination_macro_competency', '')))}</td></tr>
                  <tr><td>Domain implies stream</td>
                      <td>{html.escape(str(cv.get('domain_implied_stream', '')))}</td></tr>
                  <tr><td>Stream_Determination top-ranked stream (numeric)</td>
                      <td>{html.escape(str(cv.get('stream_determination_top_ranked_stream', '')))}
                          (dominant: {html.escape(_fmt_optional(cv.get('stream_determination_dominant_stream')))},
                          status: {html.escape(str(cv.get('stream_determination_recommendation_status', '')))})</td></tr>
                  <tr><td>Stream_Determination recommended stream (actual)</td>
                      <td>{html.escape(_fmt_optional(cv.get('stream_determination_recommended_stream')))}</td></tr>
                  <tr><td><strong>vs. numeric leader (adult_vs_numeric_agreement)</strong></td>
                      <td><strong class="{_agree_class(adult_vs_numeric)}">{_agree_label(adult_vs_numeric)}</strong></td></tr>
                  <tr><td><strong>vs. actual recommendation (adult_vs_recommended_agreement)</strong></td>
                      <td><strong class="{_agree_class(adult_vs_recommended)}">{_agree_label(adult_vs_recommended)}</strong></td></tr>
                </tbody>
              </table>
            </section>
            """

    field_derived_html = ""
    fde = report.get("field_determination_evidence")
    if fde:
        status = fde.get("data_status", "UNAVAILABLE")
        if status != "COMPUTED":
            reason = "; ".join(fde.get("warnings", [])) or "no data"
            field_derived_html = f"""
            <section class="field-derived fde-unavailable">
              <h2>Experimental: Field_Determination-derived stream evidence</h2>
              <p>Not available for this chart ({html.escape(str(status))}): {html.escape(reason)}</p>
            </section>
            """
        else:
            marks = fde.get("marks", {}) or {}
            adjusted = fde.get("adjusted_distribution", {}) or {}
            raw_dist = fde.get("raw_distribution", {}) or {}
            marks_rows = "".join(
                f"<tr><td>{html.escape(STREAM_META.get(s, {}).get('label', s))}</td>"
                f"<td class='score'>{marks.get(s, 0.0):.2f} / {FIELD_DERIVED_EVIDENCE_CAP:.0f}</td>"
                f"<td>{adjusted.get(s, 0.0):.0%} (raw {raw_dist.get(s, 0.0):.0%})</td></tr>"
                for s in ("science", "commerce", "humanities")
            )
            field_derived_html = f"""
            <section class="field-derived fde-computed">
              <h2>Experimental: Field_Determination-derived stream evidence</h2>
              <p class="cv-note">EXPERIMENTAL, DERIVED_CORRELATED evidence (default OFF; enabled for this
                 report): folds a small, capped ({FIELD_DERIVED_EVIDENCE_CAP:.0f}-point) 8th rubric section,
                 already included in each stream's score above, derived from Field_Determination's adult
                 engine run on this same chart. Not an independent astrological method -- reuses the same
                 underlying D1/D24/Jaimini/planetary-strength chart facts through the adult vocational-branch
                 lens. May include some dasha/timing-linked contribution -- see note below.</p>
              <table>
                <thead><tr><th>Stream</th><th>Marks earned</th><th>Adjusted share (raw share)</th></tr></thead>
                <tbody>{marks_rows}</tbody>
              </table>
              <p class="cv-note">
                usable fields: {fde.get('usable_field_count', 0)} &middot;
                families: {fde.get('family_count', 0)} (mapped: {fde.get('mapped_field_count', fde.get('mapped_family_count', 0))}) &middot;
                mapping coverage: {fde.get('mapping_coverage', 0.0):.0%} &middot;
                reliability: {fde.get('reliability', 0.0):.2f}
              </p>
              <p class="disclaimer">{html.escape(fde.get('note', ''))}</p>
            </section>
            """

    stream_blocks = []
    for i, s in enumerate(report.get("streams", []), 1):
        is_top = s["stream_id"] == top_ranked
        _score = max(0.0, min(100.0, float(s.get('normalized_score') or 0.0)))
        stream_blocks.append(f"""
        <section class="stream {'top' if is_top else ''}">
          <h2>{i}. {html.escape(s['label'])} <span class="sub-archetype">({html.escape(s.get('sub_archetype', 'General'))})</span>{' — Top Ranked' if is_top else ''}</h2>
          <p class="desc">{html.escape(s.get('description', ''))}</p>
          <p class="score-line">Stream score: <strong>{_score:.1f} / 100</strong></p>
          <div class="bar"><span style="width:{_score:.1f}%"></span></div>
          <!-- GAP-FIX (audit, this turn): signal_state fields were computed and
               reached the JSON report but were never rendered in HTML -- a
               parent/student reading only the HTML had no way to see the
               NEUTRAL_NO_SIGNAL vs POSITIVE_SUPPORT distinction. -->
          <p class="cv-note">
            Section signals: role_placement={html.escape(str(s.get('role_placement_signal_state', 'UNKNOWN')))},
            relational_d1={html.escape(str(s.get('relational_d1_signal_state', 'UNKNOWN')))},
            d24_confirmation={html.escape(str(s.get('d24_confirmation_signal_state', 'UNKNOWN')))}
            &middot; NEUTRAL_NO_SIGNAL means no matching pattern was found for this stream in that
            section -- it is an absence of evidence, not evidence against this stream.
          </p>
          <table>
            <thead><tr><th>Subject</th><th>Score</th><th>Astrological rationale</th></tr></thead>
            <tbody>
              {_subject_rows_html(s.get('subjects', []))}
            </tbody>
          </table>
        </section>
        """)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Early-Age Stream &amp; Subject Report — {name}</title>
<style>
  * {{ box-sizing:border-box; }}
  html {{ background:#f5f7fb; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif;
         width:min(1600px, calc(100% - 32px)); margin:0 auto; padding:24px 0 48px;
         color:#172033; line-height:1.5;
         background: linear-gradient(180deg,rgba(29,53,87,.08),transparent 260px),#f5f7fb; }}
  h1 {{ margin-bottom: 0.2rem; color:#1d3557; font-size:clamp(2rem,4vw,4rem); line-height:.98; }}
  .meta {{ color: #555; margin-bottom: 1.5rem; }}
  .streams-grid {{ display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:18px;
                   align-items:start; margin-bottom:18px; }}
  section.stream {{ min-width:0; border:1px solid #dbe3ee; border-radius:12px; padding:1.25rem 1.5rem;
                    margin:0; background:#fff; box-shadow:0 8px 24px rgba(23,32,51,.05); }}
  .streams-grid section.stream:first-child {{ grid-column:1 / -1; }}
  section.stream.top {{ border-color: #0f766e; background: #f4fbf7; }}
  .hero {{ background:#fff; border:1px solid #dbe3ee; border-radius:16px; padding:clamp(22px,3vw,40px);
           margin-bottom:18px; box-shadow:0 12px 34px rgba(23,32,51,.08); }}
  .eyebrow {{ color:#0f766e; font-size:.72rem; font-weight:800; letter-spacing:.11em; text-transform:uppercase; }}
  .hero-copy {{ color:#344054; font-size:1.05rem; max-width:900px; }}
  .metric-grid {{ display:grid; grid-template-columns:repeat(4,minmax(140px,1fr)); gap:12px; margin-top:20px; }}
  .metric {{ border:1px solid #dbe3ee; border-radius:10px; padding:12px; background:#fbfcfe; }}
  .metric b {{ display:block; color:#1d3557; font-size:1.25rem; }} .metric span {{ color:#667085; font-size:.76rem; }}
  .bar {{ height:10px; border-radius:999px; overflow:hidden; background:#e5eaf2; margin:10px 0 14px; }}
  .bar span {{ display:block; height:100%; border-radius:999px; background:linear-gradient(90deg,#0f766e,#2563eb); }}
  table {{ width:100%; border-collapse:collapse; margin-top:.75rem; table-layout:auto; }}
  th {{ text-align:left; padding:.6rem .7rem; background:#1d3557; color:#fff; font-size:.75rem; text-transform:uppercase; letter-spacing:.05em; }}
  td {{ text-align:left; padding:.55rem .7rem; border-bottom:1px solid #dbe3ee; vertical-align:top;
        overflow-wrap:anywhere; }}
  td.score {{ font-weight: 800; color:#0f766e; width: 4.5rem; }}
  .desc {{ color: #444; font-size: 0.95rem; }}
  .sub-archetype {{ font-weight: 400; font-size: 0.85rem; color: #777; }}
  .score-line {{ font-size: 1.05rem; }}
  .disclaimer {{ margin-top: 2rem; font-size: 0.85rem; color: #777; border-top: 1px solid #eee;
                 padding-top: 0.75rem; }}
  .core-tag, .elective-tag {{ font-size: 0.72rem; padding: 0.05rem 0.4rem; border-radius: 4px;
                               margin-left: 0.35rem; }}
  .core-tag {{ background: #dff0d8; color: #2a7; }}
  .elective-tag {{ background: #eee; color: #888; }}
  .contra-tag {{ font-size: 0.72rem; padding: 0.05rem 0.4rem; border-radius: 4px;
                 margin-left: 0.35rem; background: #fdecea; color: #a33; }}
  .close-call {{ background: #fff8e1; border: 1px solid #e6c568; border-radius: 6px;
                 padding: 0.75rem 1rem; margin-bottom: 1.25rem; font-size: 0.95rem; }}
  .forced-override {{ background: #fdecea; border: 1px solid #d9534f; border-radius: 6px;
                       padding: 0.75rem 1rem; margin-bottom: 1.25rem; font-size: 0.95rem;
                       font-weight: 600; color: #a33; }}
  .decision-status {{ background: #eef4ff; border: 1px solid #789; border-radius: 6px;
                       padding: 0.75rem 1rem; margin-bottom: 1.25rem; }}
  .evidence-grid {{ display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:18px; align-items:start; }}
  section.cross-validation {{ min-width:0; border:1px solid #ddd; border-radius:10px; padding:1rem 1.25rem;
                               margin:0; background:#fff; overflow-x:auto; }}
  section.cross-validation.cv-agree {{ border-color: #2a7; background: #f4fbf7; }}
  section.cross-validation.cv-disagree {{ border-color: #d9534f; background: #fdf3f2; }}
  section.cross-validation.cv-na, section.cross-validation.cv-unavailable {{ border-color: #ccc; background: #fafafa; }}
  .cv-note {{ color: #555; font-size: 0.88rem; }}
  section.field-derived {{ min-width:0; border:1px solid #ddd; border-radius:10px; padding:1rem 1.25rem;
                            margin:0; overflow-x:auto; }}
  section.field-derived.fde-computed {{ border-color: #b48; background: #fbf4f8; }}
  section.field-derived.fde-unavailable {{ border-color: #ccc; background: #fafafa; }}
  section.narrative-card {{ border:1px solid #8aa4d6; border-radius:12px; padding:1.25rem 1.5rem;
                            margin-bottom:1.25rem; background:#f8faff; }}
  .narrative-meta {{ color:#52637a; font-size:.78rem; text-transform:uppercase; letter-spacing:.04em; }}
  .narrative-grid {{ display:grid; grid-template-columns:minmax(0,.9fr) minmax(0,1.1fr); gap:clamp(24px,4vw,64px); }}
  .narrative-grid > div {{ min-width:0; }}
  .narrative-grid h2 {{ margin-bottom:.45rem; }}
  .narrative-grid p {{ margin:.45rem 0; }}
  @media (max-width:980px) {{
    body {{ width:min(100% - 20px, 900px); padding-top:10px; }}
    .metric-grid {{ grid-template-columns:repeat(2,minmax(0,1fr)); }}
    .streams-grid, .evidence-grid, .narrative-grid {{ grid-template-columns:1fr; }}
    .streams-grid section.stream:first-child {{ grid-column:auto; }}
  }}
  @media (max-width:560px) {{
    body {{ width:100%; padding:0 10px 28px; }}
    .hero, section.stream, section.narrative-card {{ padding:18px 16px; border-radius:10px; }}
    .metric-grid {{ grid-template-columns:1fr 1fr; gap:8px; }}
    .metric {{ padding:9px; }}
    th, td {{ padding:.5rem; font-size:.82rem; }}
    td.score {{ width:auto; }}
  }}
  @media print {{
    html, body {{ background:#fff; width:100%; padding:0; }}
    .hero, section.stream, section.narrative-card {{ box-shadow:none; break-inside:avoid; }}
    .streams-grid, .evidence-grid {{ display:block; }}
    section.stream, section.cross-validation, section.field-derived {{ margin-bottom:14px; }}
  }}
</style>
</head>
<body>
  <header class="hero"><div class="eyebrow">JyotishAI Stream Determination v4</div>
  <h1>{name} Stream Report</h1>
  <p class="hero-copy">Evidence-weighted exploratory guidance across Science, Commerce and Humanities, with subject-level astrological rationale.</p>
  <p class="meta">Age: {f'{age:.1f}' if isinstance(age, (int, float)) else 'not available'} &middot; Profile: {html.escape(str(report.get('calculation_profile', 'UNKNOWN')))}</p>
  <div class="metric-grid"><div class="metric"><b>{html.escape(str(recommendation_status))}</b><span>Recommendation status</span></div><div class="metric"><b>{float(report.get('evidence_completeness', 0.0)):.0%}</b><span>Evidence completeness</span></div><div class="metric"><b>{html.escape(_fmt_optional(dominant, 'None'))}</b><span>Dominant stream</span></div><div class="metric"><b>{float(report.get('score_gap_top_two', 0.0)):.1f}</b><span>Top-two score gap</span></div></div></header>
  <p class="meta">{name}{f' &middot; age {age:.1f}' if isinstance(age, (int, float)) else ''}
     &middot; {html.escape(report.get('eligibility_note', ''))}</p>
  {forced_banner}
  <div class="decision-status"><strong>Decision status:</strong> {html.escape(str(recommendation_status))}
    &middot; evidence completeness {float(report.get('evidence_completeness', 0.0)):.0%}
    {('&middot; no dominant stream is declared; rankings are exploratory only.' if not dominant else '')}
  </div>
  {(f'<div class="close-call">Note: {html.escape(str(report.get("recommendation_basis_note", "")))}</div>'
    if report.get('recommended_stream') and report.get('numeric_rank')
       and report.get('recommended_stream') != (report.get('numeric_rank') or [None])[0]
    else '')}
  {f'<div class="close-call">{html.escape(report.get("close_call_note", ""))}</div>' if report.get('is_close_call') else ''}
  {narrative_html}
  <main class="streams-grid">{''.join(stream_blocks)}</main>
  <div class="evidence-grid">{cross_validation_html}{field_derived_html}</div>
  <p class="disclaimer">{html.escape(report.get('disclaimer', ''))}</p>
</body>
</html>
"""


def write_reports(
    payload: Any, determination: Dict[str, Any], out_dir: str, *,
    forced_override: bool = False, eligibility_status: str = "NORMAL",
    cross_validation: Dict[str, Any] | None = None,
    stream_narrative: Dict[str, Any] | None = None,
) -> Dict[str, str]:
    """Write both JSON and HTML reports; returns {"json": path, "html": path}."""
    os.makedirs(out_dir, exist_ok=True)
    stem = (getattr(payload, "name", "") or "Unknown").replace(" ", "_")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    report = build_report_payload(
        payload, determination,
        forced_override=forced_override, eligibility_status=eligibility_status,
        cross_validation=cross_validation,
        stream_narrative=stream_narrative,
    )

    json_path = os.path.join(out_dir, f"stream_report_{stem}_{timestamp}.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False, default=str)

    html_path = os.path.join(out_dir, f"stream_report_{stem}_{timestamp}.html")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(render_report_html(report))

    return {"json": json_path, "html": html_path}
