/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrashnaRouteImport } from './routes/prashna'
import { Route as ParashariRouteImport } from './routes/parashari'
import { Route as PanchangaRouteImport } from './routes/panchanga'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KpRouteImport } from './routes/kp'
import { Route as KnRaoRouteImport } from './routes/kn-rao'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConfidenceRouteImport } from './routes/confidence'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as CareerTimelineRouteImport } from './routes/career-timeline'
import { Route as BirthDataRouteImport } from './routes/birth-data'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EducationAnalysisIndexRouteImport } from './routes/education-analysis/index'
import { Route as EducationAnalysisUgRouteImport } from './routes/education-analysis/ug'
import { Route as EducationAnalysisPucRouteImport } from './routes/education-analysis/puc'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrashnaRoute = PrashnaRouteImport.update({
  id: '/prashna',
  path: '/prashna',
  getParentRoute: () => rootRouteImport,
} as any)
const ParashariRoute = ParashariRouteImport.update({
  id: '/parashari',
  path: '/parashari',
  getParentRoute: () => rootRouteImport,
} as any)
const PanchangaRoute = PanchangaRouteImport.update({
  id: '/panchanga',
  path: '/panchanga',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KpRoute = KpRouteImport.update({
  id: '/kp',
  path: '/kp',
  getParentRoute: () => rootRouteImport,
} as any)
const KnRaoRoute = KnRaoRouteImport.update({
  id: '/kn-rao',
  path: '/kn-rao',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidenceRoute = ConfidenceRouteImport.update({
  id: '/confidence',
  path: '/confidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerTimelineRoute = CareerTimelineRouteImport.update({
  id: '/career-timeline',
  path: '/career-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthDataRoute = BirthDataRouteImport.update({
  id: '/birth-data',
  path: '/birth-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationAnalysisIndexRoute = EducationAnalysisIndexRouteImport.update({
  id: '/education-analysis/',
  path: '/education-analysis/',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationAnalysisUgRoute = EducationAnalysisUgRouteImport.update({
  id: '/education-analysis/ug',
  path: '/education-analysis/ug',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationAnalysisPucRoute = EducationAnalysisPucRouteImport.update({
  id: '/education-analysis/puc',
  path: '/education-analysis/puc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/birth-data': typeof BirthDataRoute
  '/career-timeline': typeof CareerTimelineRoute
  '/charts': typeof ChartsRoute
  '/confidence': typeof ConfidenceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kn-rao': typeof KnRaoRoute
  '/kp': typeof KpRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/panchanga': typeof PanchangaRoute
  '/parashari': typeof ParashariRoute
  '/prashna': typeof PrashnaRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof WorkspaceRoute
  '/education-analysis/puc': typeof EducationAnalysisPucRoute
  '/education-analysis/ug': typeof EducationAnalysisUgRoute
  '/education-analysis/': typeof EducationAnalysisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/birth-data': typeof BirthDataRoute
  '/career-timeline': typeof CareerTimelineRoute
  '/charts': typeof ChartsRoute
  '/confidence': typeof ConfidenceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kn-rao': typeof KnRaoRoute
  '/kp': typeof KpRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/panchanga': typeof PanchangaRoute
  '/parashari': typeof ParashariRoute
  '/prashna': typeof PrashnaRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof WorkspaceRoute
  '/education-analysis/puc': typeof EducationAnalysisPucRoute
  '/education-analysis/ug': typeof EducationAnalysisUgRoute
  '/education-analysis': typeof EducationAnalysisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/birth-data': typeof BirthDataRoute
  '/career-timeline': typeof CareerTimelineRoute
  '/charts': typeof ChartsRoute
  '/confidence': typeof ConfidenceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kn-rao': typeof KnRaoRoute
  '/kp': typeof KpRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/panchanga': typeof PanchangaRoute
  '/parashari': typeof ParashariRoute
  '/prashna': typeof PrashnaRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof WorkspaceRoute
  '/education-analysis/puc': typeof EducationAnalysisPucRoute
  '/education-analysis/ug': typeof EducationAnalysisUgRoute
  '/education-analysis/': typeof EducationAnalysisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/birth-data'
    | '/career-timeline'
    | '/charts'
    | '/confidence'
    | '/forgot-password'
    | '/kn-rao'
    | '/kp'
    | '/login'
    | '/marketplace'
    | '/panchanga'
    | '/parashari'
    | '/prashna'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/workspace'
    | '/education-analysis/puc'
    | '/education-analysis/ug'
    | '/education-analysis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/birth-data'
    | '/career-timeline'
    | '/charts'
    | '/confidence'
    | '/forgot-password'
    | '/kn-rao'
    | '/kp'
    | '/login'
    | '/marketplace'
    | '/panchanga'
    | '/parashari'
    | '/prashna'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/workspace'
    | '/education-analysis/puc'
    | '/education-analysis/ug'
    | '/education-analysis'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/birth-data'
    | '/career-timeline'
    | '/charts'
    | '/confidence'
    | '/forgot-password'
    | '/kn-rao'
    | '/kp'
    | '/login'
    | '/marketplace'
    | '/panchanga'
    | '/parashari'
    | '/prashna'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/workspace'
    | '/education-analysis/puc'
    | '/education-analysis/ug'
    | '/education-analysis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  BirthDataRoute: typeof BirthDataRoute
  CareerTimelineRoute: typeof CareerTimelineRoute
  ChartsRoute: typeof ChartsRoute
  ConfidenceRoute: typeof ConfidenceRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  KnRaoRoute: typeof KnRaoRoute
  KpRoute: typeof KpRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PanchangaRoute: typeof PanchangaRoute
  ParashariRoute: typeof ParashariRoute
  PrashnaRoute: typeof PrashnaRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  WorkspaceRoute: typeof WorkspaceRoute
  EducationAnalysisPucRoute: typeof EducationAnalysisPucRoute
  EducationAnalysisUgRoute: typeof EducationAnalysisUgRoute
  EducationAnalysisIndexRoute: typeof EducationAnalysisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prashna': {
      id: '/prashna'
      path: '/prashna'
      fullPath: '/prashna'
      preLoaderRoute: typeof PrashnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parashari': {
      id: '/parashari'
      path: '/parashari'
      fullPath: '/parashari'
      preLoaderRoute: typeof ParashariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panchanga': {
      id: '/panchanga'
      path: '/panchanga'
      fullPath: '/panchanga'
      preLoaderRoute: typeof PanchangaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kp': {
      id: '/kp'
      path: '/kp'
      fullPath: '/kp'
      preLoaderRoute: typeof KpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kn-rao': {
      id: '/kn-rao'
      path: '/kn-rao'
      fullPath: '/kn-rao'
      preLoaderRoute: typeof KnRaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidence': {
      id: '/confidence'
      path: '/confidence'
      fullPath: '/confidence'
      preLoaderRoute: typeof ConfidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-timeline': {
      id: '/career-timeline'
      path: '/career-timeline'
      fullPath: '/career-timeline'
      preLoaderRoute: typeof CareerTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birth-data': {
      id: '/birth-data'
      path: '/birth-data'
      fullPath: '/birth-data'
      preLoaderRoute: typeof BirthDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education-analysis/': {
      id: '/education-analysis/'
      path: '/education-analysis'
      fullPath: '/education-analysis/'
      preLoaderRoute: typeof EducationAnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education-analysis/ug': {
      id: '/education-analysis/ug'
      path: '/education-analysis/ug'
      fullPath: '/education-analysis/ug'
      preLoaderRoute: typeof EducationAnalysisUgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education-analysis/puc': {
      id: '/education-analysis/puc'
      path: '/education-analysis/puc'
      fullPath: '/education-analysis/puc'
      preLoaderRoute: typeof EducationAnalysisPucRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  BirthDataRoute: BirthDataRoute,
  CareerTimelineRoute: CareerTimelineRoute,
  ChartsRoute: ChartsRoute,
  ConfidenceRoute: ConfidenceRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  KnRaoRoute: KnRaoRoute,
  KpRoute: KpRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  PanchangaRoute: PanchangaRoute,
  ParashariRoute: ParashariRoute,
  PrashnaRoute: PrashnaRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  WorkspaceRoute: WorkspaceRoute,
  EducationAnalysisPucRoute: EducationAnalysisPucRoute,
  EducationAnalysisUgRoute: EducationAnalysisUgRoute,
  EducationAnalysisIndexRoute: EducationAnalysisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
