"""jyotish/career_field_report_v2.py — Parent/Student-Friendly Career Field
Recommendation Report (14-section format).

This module produces the exact report structure requested by the user:
  1. Executive Summary
  2. Final Recommendation Snapshot
  3. Astrological Career Signature
  4. Final Macro-Cluster Ranking
  5. Corrected Top 20 Fields
  6. Education Route Mapping (3 routes: Primary / High-End Specialised / Safe Backup)
  7. Fields to Avoid as Primary
  8. Engine Output Comparison (raw engine rank vs corrected/final status)
  9. Engine Gap Diagnosis
  10. Final Student-Friendly Recommendation
  11. Parent Report Version
  12. Student Version
  13. (JSON schema — embedded as <script type="application/json"> in the HTML)
  14. Fixed section order (enforced by this file's rendering order)

Design
------
Everything that is DETERMINISTIC (scores, ranks, dasha lords, macro-cluster
membership, age-based career phase) comes straight from the existing engine
(`jyotish.engine.run_engine`) — nothing is re-invented or guessed.

Everything that requires JUDGEMENT / NARRATIVE — the one-line career identity,
the astrological-signature interpretation, education-route mapping, the
avoid-list reasoning, the engine-gap audit, and the parent/student prose — is
explicitly marked "LLM" per the user's instruction, and is generated by a
single structured call to the already-configured LLM provider
(jyotish/llm.py — Gemini by default, Anthropic/OpenAI as configured in .env).

If no LLM API key is configured, the report is still produced with clearly
labelled deterministic fallbacks so the file never silently omits a section.
"""
from __future__ import annotations

import json
import logging
import os
from datetime import datetime
from typing import Any, Dict, List, Optional

logger = logging.getLogger("jyotish_engine_v11_0")

# ---------------------------------------------------------------------------
# Internal engine imports (reuse existing, do not duplicate logic)
# ---------------------------------------------------------------------------
from .payload import NatalPayloadV2, ENGINE_VERSION
from .astro import _get_active_dasha_lord, _calc_age
from .engine import run_engine, classify_age_stage, _resolve_career_phase
from .engine_io import parse_json_payload
from .llm import _LLM_PROVIDERS, _ProviderClientWrapper, _run_llm_with_retry

from .career_field_utils import _field_display_name, _print_macro_cluster


# =============================================================================
# 1. DETERMINISTIC DATA ASSEMBLY
# =============================================================================

def _macro_cluster_ranking(results: List[Dict], top_n: int = 20) -> List[Dict]:
    """Group the top-N fields by macro-cluster and rank clusters by weighted score."""
    grouped: Dict[str, List[Dict]] = {}
    order: List[str] = []
    for rank, row in enumerate(results[:top_n], 1):
        cluster = _print_macro_cluster(row)
        grouped.setdefault(cluster, []).append({**row, "_rank": rank})
        if cluster not in order:
            order.append(cluster)

    def _cluster_strength(rows: List[Dict]) -> float:
        # Weighted by rank position (higher rank = more weight) and final_score.
        return sum((top_n + 1 - r["_rank"]) * float(r.get("final_score", 0.0) or 0.0) for r in rows)

    ranked = sorted(
        ((c, grouped[c]) for c in order),
        key=lambda kv: -_cluster_strength(kv[1]),
    )
    max_strength = _cluster_strength(ranked[0][1]) if ranked else 1.0
    out = []
    for i, (cluster, rows) in enumerate(ranked, 1):
        strength = _cluster_strength(rows)
        pct = round(100 * strength / max_strength, 0) if max_strength else 0
        out.append({
            "rank": i,
            "cluster": cluster,
            "strength_pct": pct,
            "member_fields": [_field_display_name(r) for r in rows],
            "best_rank_in_cluster": min(r["_rank"] for r in rows),
        })
    return out


def _build_chart_signature_facts(payload: NatalPayloadV2, active_lord: str, peak_lord: str) -> Dict[str, Any]:
    """Pull the raw chart facts (no interpretation) that the LLM will explain."""
    house_lords = getattr(payload, "house_lords", {}) or {}
    dob = getattr(payload, "dob", "") or ""
    ug_start_year = ""
    try:
        # Indian UG admission normally follows the Class 12 year. Students born
        # after the Sep admission cutoff usually join in the next calendar year.
        birth_dt = datetime.strptime(str(dob), "%Y-%m-%d")
        ug_start_year = birth_dt.year + (19 if birth_dt.month >= 10 else 18)
    except Exception:
        current_age = float(getattr(payload, "current_age", 0) or 0)
        if current_age:
            ug_start_year = datetime.now().year + max(0, int(round(18 - current_age)))
    return {
        "lagna_sign": getattr(payload, "lagna_sign", "") or getattr(payload, "ascendant_sign", ""),
        "h10_lord": house_lords.get(10, house_lords.get("10", "")),
        "active_mahadasha_lord": active_lord,
        "peak_career_mahadasha_lord": peak_lord,
        "dob": dob,
        "current_age": getattr(payload, "current_age", 0),
        "ug_start_year": ug_start_year,
        "eff_strengths_top3": sorted(
            (getattr(payload, "eff_strengths", {}) or {}).items(), key=lambda x: -x[1]
        )[:3],
        "arudha_lagna": getattr(payload, "arudha_lagna", ""),
        "arudha_pada_h10": getattr(payload, "arudha_pada_h10", ""),
        "academic_tier_recommendation": getattr(payload, "academic_tier_recommendation", {}) or {},
        "edu_stream": getattr(payload, "edu_stream", {}) or {},
    }


def _career_phase_label(age_stage: Dict, career_phase_raw: str) -> str:
    stage = age_stage.get("stage", "")
    mapping = {
        "class_9_10": "Class 9-10",
        "class_11_12": "Class 11-12",
        "adult": career_phase_raw.replace("_", " ").title() if career_phase_raw else "Working Professional",
    }
    return mapping.get(stage, career_phase_raw.replace("_", " ").title() if career_phase_raw else "Adult")


# =============================================================================
# 2. LLM CALL — one structured call for every judgement/narrative field
# =============================================================================

_REPORT_SYSTEM_PROMPT = """You are an expert Jyotish (Vedic Astrology) career analyst writing an \
auditable, parent/student-friendly Career Field Recommendation Report.

You are given: (1) raw chart facts, (2) the deterministic engine's top-35 \
career fields with scores, and (3) macro-cluster groupings already computed \
by the engine. Your job is ONLY interpretation and narrative — you must NOT \
invent scores, ranks, or fields that are not present in the provided data.

Rules:
- Every field you name in top_20_fields, education_routes, or demoted_fields \
  MUST come from the provided field list (use the exact field_label given).
- macro_clusters MUST use the exact cluster names and strengths given — you \
  only add the "interpretation" text.
- Do not fabricate specific institutions unless they are well known, real \
  target examples (IITs, NITs, IISc, ISRO, DRDO, BARC, CSIR, top state \
  universities) appropriate to the fields given.
- Confidence should reflect how concentrated the top macro-cluster strength is \
  relative to the rest (a dominant #1 cluster = High/Medium-High; a flat \
  distribution = Medium/Exploratory).
- Keep prose concise, plain-English, non-repetitive.

Return ONLY a single valid JSON object matching exactly this schema (no markdown fences):
{
  "final_identity": {
    "macro_identity": "one short phrase, e.g. Advanced Materials, Physical Engineering & Space Systems",
    "one_line_summary": "one sentence: UG direction + PG direction + career direction",
    "confidence": "High | Medium-High | Medium | Exploratory"
  },
  "snapshot": {
    "best_ug_route": "",
    "best_pg_route": "",
    "best_career_cluster": "",
    "strong_backup_route": "",
    "avoid_as_primary": "",
    "best_working_style": ""
  },
  "astrological_signature": [
    {"factor": "Lagna / Lagna lord", "observation": "", "career_meaning": ""},
    {"factor": "10th house / 10th lord", "observation": "", "career_meaning": ""},
    {"factor": "D10 career chart", "observation": "", "career_meaning": ""},
    {"factor": "D24 education chart", "observation": "", "career_meaning": ""},
    {"factor": "Strong planets", "observation": "", "career_meaning": ""},
    {"factor": "Dasha support", "observation": "", "career_meaning": ""},
    {"factor": "KP confirmation", "observation": "", "career_meaning": ""}
  ],
  "macro_cluster_interpretations": [
    {"cluster": "<must match a provided cluster name exactly>", "interpretation": ""}
  ],
  "top_20_fields": [
    {"field": "<must match a provided field_label exactly>", "recommended_level": "Primary | Strong alternative | Backup | PG Specialisation | Specialised | Explore", "reason": "<=20 words"}
  ],
  "education_routes": [
    {
      "route_name": "Route A - Primary Route",
      "title": "",
      "ug_options": "",
      "pg_options": "",
      "phd_options": "",
      "careers": "",
      "best_for": "",
      "risk_level": "Low | Low-Medium | Medium | Medium-High | High",
      "long_term_value": "Good | High | Very High"
    },
    {"route_name": "Route B - High-End Specialised Route", "title": "", "ug_options": "", "pg_options": "", "phd_options": "", "careers": "", "best_for": "", "risk_level": "", "long_term_value": ""},
    {"route_name": "Route C - Safe Practical Backup", "title": "", "ug_options": "", "pg_options": "", "careers": "", "best_for": "", "risk_level": "", "long_term_value": "", "phd_options": ""}
  ],
  "fields_to_avoid": [
    {"field": "", "status": "Avoid as primary | Exploratory only | Avoid unless strong interest", "reason": ""}
  ],
  "engine_output_comparison": [
    {"engine_rank": 1, "engine_field": "<must match a provided field_label>", "correct_status": "Correct | Over-ranked | Under-ranked | Partial | False positive | Correct but under-ranked", "action": "Keep | Demote | Demote to secondary | Promote | Remove/demote"}
  ],
  "engine_gap_audit": [
    {"gap_no": 1, "gap": "", "effect": "", "fix": ""}
  ],
  "parent_summary": "2-3 plain-English sentences for a parent, no jargon.",
  "student_summary": "2-3 plain-English sentences addressed to the student, no jargon.",
  "final_recommendation": "One blockquote-style paragraph naming the primary field identity, best UG/PG/career direction, and which demoted fields to avoid and why."
}
"""


def _build_report_user_prompt(
    student_name: str,
    career_phase: str,
    active_lord: str,
    peak_lord: str,
    chart_facts: Dict[str, Any],
    top35: List[Dict],
    macro_clusters: List[Dict],
) -> str:
    field_lines = []
    for rank, r in enumerate(top35[:35], 1):
        field_lines.append({
            "rank": rank,
            "field_label": _field_display_name(r),
            "domain": r.get("domain", ""),
            "final_score": round(float(r.get("final_score", 0.0) or 0.0), 3),
            "macro_cluster": _print_macro_cluster(r),
        })

    return f"""--- STUDENT / CLIENT ---
Name: {student_name}
Career phase: {career_phase}
Active Mahadasha lord: {active_lord}
Peak career Mahadasha lord: {peak_lord}

--- RAW CHART FACTS (do not contradict) ---
{json.dumps(chart_facts, indent=2, default=str)}

--- ENGINE MACRO-CLUSTER RANKING (top 20, already computed — do not change strengths) ---
{json.dumps(macro_clusters, indent=2)}

--- ENGINE TOP-35 FIELDS (deterministic ranking + scores — do not change ranks/scores) ---
{json.dumps(field_lines, indent=2)}

Using ONLY the fields, clusters, and facts above, produce the JSON object described in the system prompt.
"""


def _validate_report_json(data: Dict) -> None:
    required = [
        "final_identity", "snapshot", "astrological_signature",
        "macro_cluster_interpretations", "top_20_fields", "education_routes",
        "fields_to_avoid", "engine_output_comparison", "engine_gap_audit",
        "parent_summary", "student_summary", "final_recommendation",
    ]
    missing = [k for k in required if k not in data]
    if missing:
        raise ValueError(f"Missing required keys: {missing}")


def _call_llm_for_report(
    student_name: str,
    career_phase: str,
    active_lord: str,
    peak_lord: str,
    chart_facts: Dict[str, Any],
    top35: List[Dict],
    macro_clusters: List[Dict],
) -> Optional[Dict]:
    """Single structured LLM call producing every narrative/judgement field in the report."""
    try:
        from .engine_io import _maybe_load_dotenv as _dotenv_fn
        _dotenv_fn()
    except Exception:
        pass

    provider_name = os.getenv("LLM_PROVIDER", "gemini").lower()
    env_var, default_model, call_fn = _LLM_PROVIDERS.get(provider_name, _LLM_PROVIDERS["gemini"])
    model_override = os.getenv("LLM_MODEL", default_model)
    api_key = os.getenv(env_var)
    if not api_key:
        logger.warning("%s missing (provider=%s) — report will use deterministic fallback text.", env_var, provider_name)
        return None

    client = _ProviderClientWrapper(call_fn, api_key, model_override)
    user_prompt = _build_report_user_prompt(
        student_name, career_phase, active_lord, peak_lord, chart_facts, top35, macro_clusters
    )
    messages = [
        {"role": "system", "content": _REPORT_SYSTEM_PROMPT},
        {"role": "user", "content": user_prompt},
    ]
    schema = {"schema": {"required": [], "properties": {}}}  # structure hint embedded in system prompt already
    return _run_llm_with_retry(client, messages, schema, _validate_report_json, max_retries=3)


# =============================================================================
# 3. DETERMINISTIC FALLBACK (used only if no LLM key is configured / call fails)
# =============================================================================

def _fallback_report_json(top35: List[Dict], macro_clusters: List[Dict], student_name: str) -> Dict:
    top1 = _field_display_name(top35[0]) if top35 else "Undetermined"
    top_cluster = macro_clusters[0]["cluster"] if macro_clusters else "Undetermined"
    note = "[LLM unavailable — deterministic placeholder; set an LLM_PROVIDER API key in .env for full narrative]"
    return {
        "final_identity": {
            "macro_identity": top_cluster,
            "one_line_summary": f"Primary direction: {top1}. {note}",
            "confidence": "Medium",
        },
        "snapshot": {
            "best_ug_route": top1, "best_pg_route": top1, "best_career_cluster": top_cluster,
            "strong_backup_route": _field_display_name(top35[1]) if len(top35) > 1 else "",
            "avoid_as_primary": "See Fields to Avoid section", "best_working_style": note,
        },
        "astrological_signature": [
            {"factor": f, "observation": note, "career_meaning": ""}
            for f in ["Lagna / Lagna lord", "10th house / 10th lord", "D10 career chart",
                      "D24 education chart", "Strong planets", "Dasha support", "KP confirmation"]
        ],
        "macro_cluster_interpretations": [
            {"cluster": c["cluster"], "interpretation": note} for c in macro_clusters
        ],
        "top_20_fields": [
            {"field": _field_display_name(r), "recommended_level": "Explore", "reason": note}
            for r in top35[:20]
        ],
        "education_routes": [
            {"route_name": "Route A - Primary Route", "title": top1, "ug_options": note, "pg_options": "",
             "phd_options": "", "careers": "", "best_for": "", "risk_level": "Medium", "long_term_value": "High"}
        ],
        "fields_to_avoid": [],
        "engine_output_comparison": [
            {"engine_rank": i + 1, "engine_field": _field_display_name(r), "correct_status": "Correct", "action": "Keep"}
            for i, r in enumerate(top35[:10])
        ],
        "engine_gap_audit": [{"gap_no": 1, "gap": note, "effect": "", "fix": ""}],
        "parent_summary": note,
        "student_summary": note,
        "final_recommendation": note,
    }


# =============================================================================
# 4. HTML RENDERING
# =============================================================================

def _esc(text: Any) -> str:
    return (str(text if text is not None else "")
            .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;"))


def _table(headers: List[str], rows: List[List[str]]) -> str:
    thead = "".join(f"<th>{_esc(h)}</th>" for h in headers)
    tbody = "".join(
        "<tr>" + "".join(f"<td>{c}</td>" for c in row) + "</tr>" for row in rows
    )
    return f"<table><thead><tr>{thead}</tr></thead><tbody>{tbody}</tbody></table>"


def render_report_html_rich(
    student_name: str,
    career_phase: str,
    active_lord: str,
    peak_lord: str,
    top35: List[Dict],
    macro_clusters: List[Dict],
    report: Dict,
    chart_facts: Optional[Dict[str, Any]] = None,
) -> str:
    """Rich/hero-style dashboard HTML for the Career Field Recommendation Report.

    RECONSTRUCTED 2026-07-06: this visual format (hero banner, sidebar rail,
    verdict cards, field-card grid, method/SBC evidence canvases) previously
    existed in this codebase and produced files like
    educational_records/career_field_report_samyuhtha_20260705_200548.html,
    but its generating source was lost (same truncation/corruption pattern
    found elsewhere in web_report.py — see the 2026-07-06 fixes there). No
    copy of the original generator survived anywhere in the repo, only its
    HTML output (4 sample files), so this is a clean rebuild from those
    samples' surviving markup/CSS, using the exact same inputs/data already
    computed by render_report_html() above (nothing new is invented).

    Known simplifications vs. the original samples (data for these was not
    available from any current code path, only inferable from static HTML):
      - Education route cards use a plain UG/PG/Careers text layout instead
        of the original hand-positioned SVG flow-diagram per route.
      - The "Potential colleges from registry" pill list per route is
        omitted (no per-field college registry lookup exists in the current
        report/chart_facts data).
    Everything else (hero identity, verdict snapshot, field scores, full
    field matrix, macro-cluster ranking, evidence table + method/SBC
    canvases, execution timeline, parent/student prose, gap diagnosis,
    final recommendation, JSON schema) is reconstructed 1:1 against the
    surviving samples' section structure.
    """
    gen_date = datetime.now().strftime("%d %b %Y, %H:%M")
    fi = report.get("final_identity", {}) or {}
    snap = report.get("snapshot", {}) or {}
    chart_facts = chart_facts or {}

    def score_value(row: Dict) -> float:
        return round(float((row or {}).get("final_score", 0.0) or 0.0), 2)

    def level_class(level: str) -> str:
        l = (level or "").lower()
        if "primary" in l:
            return "primary"
        if "strong" in l or "special" in l:
            return "strong"
        if "backup" in l or "pg" in l:
            return "backup"
        return "explore"

    def pills(items: List[str], cls: str = "") -> str:
        klass = f"pill {cls}".strip()
        return "".join(f'<span class="{klass}">{_esc(i)}</span>' for i in items if str(i or "").strip())

    top1 = top35[0] if top35 else {}
    top2 = top35[1] if len(top35) > 1 else {}
    top3 = top35[2] if len(top35) > 2 else {}
    top1_label = _field_display_name(top1) if top1 else (snap.get("best_ug_route") or "Undetermined")
    top2_label = _field_display_name(top2) if top2 else (snap.get("strong_backup_route") or "")
    top3_label = _field_display_name(top3) if top3 else (snap.get("best_pg_route") or "")
    top_cluster = macro_clusters[0] if macro_clusters else {"cluster": fi.get("macro_identity", ""), "strength_pct": 0}
    field_llm = {f.get("field"): f for f in report.get("top_20_fields", [])}
    interp_map = {i.get("cluster"): i.get("interpretation", "") for i in report.get("macro_cluster_interpretations", [])}

    # ── Hero ───────────────────────────────────────────────────────────────
    meta_chips = (
        f'<span class="chip strong">Primary identity: {_esc(fi.get("macro_identity",""))}</span>'
        f'<span class="chip blue">Career phase: {_esc(career_phase)}</span>'
        f'<span class="chip">Active Mahadasha: {_esc(active_lord)}</span>'
        f'<span class="chip">Peak Career Mahadasha: {_esc(peak_lord)}</span>'
        f'<span class="chip warn">Generated: {gen_date}</span>'
    )
    hero_html = f"""
  <header class="hero">
    <div class="hero-main">
      <div><div class="eyebrow">JyotishAI Career Engine {_esc(ENGINE_VERSION)}</div><h1>{_esc(student_name)} Career Field Report</h1></div>
      <p class="hero-copy">{_esc(fi.get("one_line_summary",""))}</p>
      <div class="meta-row">{meta_chips}</div>
    </div>
    <aside class="hero-side">
      <div class="section-title"><h2>Decision Snapshot</h2></div>
      <div class="metric-grid">
        <div class="metric"><b>{top_cluster.get("strength_pct",0):.0f}%</b><span>Dominant macro-cluster strength</span></div>
        <div class="metric"><b>{score_value(top1):.2f}</b><span>Top normalized field score</span></div>
        <div class="metric"><b>{_esc(fi.get("confidence",""))}</b><span>Final recommendation confidence</span></div>
        <div class="metric"><b>{min(20,len(top35))}</b><span>Fields shown in priority matrix</span></div>
      </div>
      <div class="callout"><strong>Plain answer:</strong> {_esc(top1_label)} is the cleanest starting point. {_esc(top3_label)} is the best specialization direction.</div>
    </aside>
  </header>"""

    # ── Sidebar rail ─────────────────────────────────────────────────────────
    strengths_top3 = chart_facts.get("eff_strengths_top3", []) or []
    signature_pills = pills([
        chart_facts.get("lagna_sign", ""),
        f'H10 lord: {chart_facts.get("h10_lord","")}' if chart_facts.get("h10_lord") else "",
        f'Active: {active_lord}' if active_lord else "",
        f'Peak: {peak_lord}' if peak_lord else "",
    ], "primary") + pills([p for p, _ in strengths_top3], "alt")
    avoid_pills = pills([a.get("field", "") for a in report.get("fields_to_avoid", [])], "avoid")

    rail_html = f"""
    <aside class="rail">
      <section class="panel"><div class="section-title"><h2>Best Choices</h2></div><div class="small-list">
        <p><b>UG:</b> {_esc(top1_label)}</p>
        <p><b>PG:</b> {_esc(top3_label)}</p>
        <p><b>Backup:</b> {_esc(top2_label)}</p>
        <p><b>Work style:</b> {_esc(snap.get("best_working_style",""))}</p>
      </div></section>
      <section class="panel"><div class="section-title"><h2>Chart Signature</h2></div><div class="pill-wrap">{signature_pills}</div><p class="note" style="margin-top:10px;">These are factual chart anchors passed to the LLM interpretation layer.</p></section>
      <section class="panel"><div class="section-title"><h2>Avoid As Primary</h2></div><div class="pill-wrap">{avoid_pills}</div><p class="note" style="margin-top:10px;">Use these only as backups or interest areas unless the student has strong independent motivation.</p></section>
    </aside>"""

    # ── 1. Verdict snapshot ──────────────────────────────────────────────────
    section1 = f"""
      <section class="panel"><div class="section-title"><h2>1. Final Recommendation Snapshot</h2><span class="chip strong">Actionable</span></div><div class="verdict">
        <div class="verdict-card"><div class="label">Best UG Route</div><div class="value">{_esc(top1_label)}</div><p class="note">Main education decision.</p></div>
        <div class="verdict-card"><div class="label">Strong Backup</div><div class="value">{_esc(top2_label)}</div><p class="note">Keep available, but secondary to the primary field identity.</p></div>
        <div class="verdict-card"><div class="label">Best PG Route</div><div class="value">{_esc(top3_label)}</div><p class="note">Specialization direction after the core UG base.</p></div>
        <div class="verdict-card"><div class="label">Career Cluster</div><div class="value">{_esc(top_cluster.get("cluster",""))}</div><p class="note">Dominant macro identity from engine cluster ranking.</p></div>
      </div></section>"""

    # ── 2. Top field scores (two columns of 10) ─────────────────────────────
    def score_rows_html(rows: List[Dict], start_rank: int) -> str:
        out = []
        for i, r in enumerate(rows, start_rank):
            sc = score_value(r)
            out.append(
                f'<div class="score-row"><span class="rank">{i}</span><div>'
                f'<div class="score-name">{_esc(_field_display_name(r))}</div>'
                f'<div class="bar"><span style="width:{max(0,min(100,sc)):.2f}%"></span></div>'
                f'</div><div class="score-num">{sc:.2f}</div></div>'
            )
        return "".join(out)

    top20 = top35[:20]
    half = (len(top20) + 1) // 2
    section2 = f"""
      <section class="panel"><div class="section-title"><h2>2. Top Field Scores</h2><span class="chip">Engine normalized scale</span></div><div class="two-col">
        <div class="score-list">{score_rows_html(top20[:half], 1)}</div>
        <div class="score-list">{score_rows_html(top20[half:], half+1)}</div>
      </div><p class="note" style="margin-top:12px;">Scores are rendered on the engine's normalized display scale. They are not multiplied again into four-digit percentages.</p></section>"""

    # ── 3. Education route map (simplified — no per-route SVG/colleges) ────
    route_cards = []
    for route in report.get("education_routes", []):
        risk = route.get("risk_level", "")
        value = route.get("long_term_value", "")
        route_cards.append(f"""
          <article class="route">
            <div class="route-head"><small>{_esc(route.get("route_name",""))}</small><h3>{_esc(route.get("title",""))}</h3></div>
            <div class="route-body">
              <div class="small-list">
                <p><b>UG:</b> {_esc(route.get("ug_options",""))}</p>
                <p><b>PG:</b> {_esc(route.get("pg_options",""))}</p>
                <p><b>PhD:</b> {_esc(route.get("phd_options",""))}</p>
                <p><b>Careers:</b> {_esc(route.get("careers",""))}</p>
                <p><b>Best for:</b> {_esc(route.get("best_for",""))}</p>
              </div>
              <div class="pill-wrap">{pills([risk, value])}</div>
            </div>
          </article>""")
    section3 = f"""
      <section class="panel"><div class="section-title"><h2>3. Education Route Map</h2><span class="chip blue">UG to PG to career</span></div><div class="three-col">{"".join(route_cards)}</div></section>"""

    # ── 4. Full top 20 field matrix ─────────────────────────────────────────
    field_cards = []
    for r in top20:
        label = _field_display_name(r)
        llm_f = field_llm.get(label, {})
        sc = score_value(r)
        level = llm_f.get("recommended_level", "Explore")
        field_cards.append(
            f'<article class="field-card"><div class="field-top">'
            f'<div class="field-title">{_esc(label)}</div><div class="field-score">{sc:.2f}</div>'
            f'</div><span class="level {level_class(level)}">{_esc(level)}</span>'
            f'<p>{_esc(llm_f.get("reason",""))}</p></article>'
        )
    section4 = f"""
      <section class="panel"><div class="section-title"><h2>4. Full Top 20 Field Matrix</h2><span class="chip">Use as priority order</span></div><div class="field-grid">{"".join(field_cards)}</div></section>"""

    # ── 5. Macro-cluster ranking ─────────────────────────────────────────────
    mc_rows = "".join(
        f'<tr><td>{c["rank"]}</td><td>{_esc(c["cluster"])}</td><td><strong>{c["strength_pct"]:.0f}%</strong></td>'
        f'<td>{_esc(interp_map.get(c["cluster"], ""))}</td></tr>'
        for c in macro_clusters
    )
    section5 = f"""
      <section class="panel"><div class="section-title"><h2>5. Macro-Cluster Ranking</h2><span class="chip strong">Deterministic + interpretation</span></div>
      <table class="matrix"><thead><tr><th>Rank</th><th>Macro Cluster</th><th>Strength</th><th>Career Meaning</th></tr></thead><tbody>{mc_rows}</tbody></table></section>"""

    # ── 6. Evidence from chart data (+ method/SBC canvases) ─────────────────
    sig_rows = "".join(
        f'<tr><td>{_esc(r.get("factor",""))}</td><td>{_esc(r.get("observation",""))}</td><td>{_esc(r.get("career_meaning",""))}</td></tr>'
        for r in report.get("astrological_signature", [])
    )
    method_labels = [("knrao_score", "K.N. Rao"), ("kp_score", "KP"), ("dashamsha_score", "D10")]
    method_cards = []
    for i, r in enumerate(top35[:3], 1):
        bars = "".join(
            f'<div class="method-bar-row"><span class="method-name">{name}</span>'
            f'<div class="method-track"><span style="width:{float(r.get(key,0) or 0):.1f}%"></span></div>'
            f'<span class="method-pct">{float(r.get(key,0) or 0):.1f}%</span></div>'
            for key, name in method_labels
        )
        method_cards.append(
            f'<div class="method-card"><div class="method-title"><span>#{i}</span>{_esc(_field_display_name(r))}</div>'
            f'<div class="method-bars">{bars}</div></div>'
        )
    sbc_rows = []
    for i, r in enumerate(top35[:3], 1):
        smi = float(r.get("smi", 0) or 0)
        band = r.get("timing_band", "")
        sbc_rows.append(
            f'<div class="sbc-row"><div class="sbc-rank">#{i}</div><div class="sbc-main">'
            f'<div class="sbc-label">{_esc(_field_display_name(r))}</div>'
            f'<div class="sbc-track"><span style="width:{smi:.1f}%"></span></div></div>'
            f'<div class="sbc-pct">{smi:.1f}%</div><div class="sbc-band">{_esc(band)}</div></div>'
        )
    ug_start_year = chart_facts.get("ug_start_year", "")
    has_sbc = any(r.get("smi") is not None for r in top35[:3])
    sbc_block = (
        f"""<div class="sbc-canvas"><div class="sbc-head"><div><small>SBC timing canvas</small><h3>UG start year: {_esc(str(ug_start_year))}</h3></div><span class="chip blue">Top 3 courses</span></div>
            <div class="sbc-bars">{"".join(sbc_rows)}</div>
            <p class="note">SBC is an event-timing layer: it estimates manifestation support for the admission/start year, while aptitude ranking remains unchanged.</p></div>"""
        if has_sbc else ""
    )
    section6 = f"""
      <section class="panel"><div class="section-title"><h2>6. Evidence From Chart Data</h2><span class="chip">Why this direction</span></div><div class="two-col">
        <table class="matrix"><thead><tr><th>Factor</th><th>Observation</th><th>Career Meaning</th></tr></thead><tbody>{sig_rows}</tbody></table>
        <div><div class="method-canvas"><div class="sbc-head"><div><small>Method score canvas</small><h3>Top 3 course validation</h3></div><span class="chip strong">K.N. Rao + KP + D10</span></div>
          <div class="method-grid">{"".join(method_cards)}</div>
          <p class="note">These are independent method witnesses for each course. The final rank still uses the engine blend and macro-cluster logic.</p></div>
        {sbc_block}</div>
      </div></section>"""

    # ── 7. Execution timeline ────────────────────────────────────────────────
    timeline_html = ""
    try:
        y0 = int(ug_start_year)
        phases = [
            (y0 - 1, y0, "Strengthen fundamentals aligned with the recommended UG route."),
            (y0, y0 + 2, "Build the core technical base, tools, projects, and disciplined study rhythm."),
            (y0 + 2, y0 + 4, "Use internships, projects, and electives to test the strongest specializations."),
            (y0 + 4, y0 + 7, "Move toward the PG route and career cluster identified by this report."),
        ]
        timeline_html = "".join(
            f'<div class="timebox"><b>{a}-{b}</b><p>{_esc(txt)}</p></div>' for a, b, txt in phases
        )
    except (TypeError, ValueError):
        pass
    section7 = f"""
      <section class="panel"><div class="section-title"><h2>7. Execution Timeline</h2><span class="chip blue">Student-friendly</span></div><div class="timeline">{timeline_html}</div></section>""" if timeline_html else ""

    # ── 8. Parent / student versions ────────────────────────────────────────
    section8 = f"""
      <section class="panel"><div class="section-title"><h2>8. Parent and Student Versions</h2></div><div class="two-col">
        <div class="callout"><strong>Parent version:</strong> {_esc(report.get("parent_summary",""))}</div>
        <div class="callout"><strong>Student version:</strong> {_esc(report.get("student_summary",""))}</div>
      </div></section>"""

    # ── 9. Engine gap diagnosis ──────────────────────────────────────────────
    audit_cards = "".join(
        f'<div class="audit-card"><b>{_esc(g.get("gap",""))}</b><p>{_esc(g.get("effect",""))}</p><p><strong>Fix:</strong> {_esc(g.get("fix",""))}</p></div>'
        for g in report.get("engine_gap_audit", [])
    )
    section9 = f"""
      <section class="panel"><div class="section-title"><h2>9. Engine Gap Diagnosis</h2><span class="chip warn">Audit</span></div><div class="audit-grid">{audit_cards}</div></section>""" if audit_cards else ""

    # ── 10. Final recommendation ─────────────────────────────────────────────
    section10 = f"""
      <section class="panel"><div class="section-title"><h2>10. Final Recommendation</h2><span class="chip strong">Summary</span></div><div class="callout">&gt; {_esc(report.get("final_recommendation",""))}</div></section>"""

    # ── 11. Machine-readable JSON ────────────────────────────────────────────
    json_schema_payload = {
        "student_profile": {
            "name": student_name, "career_phase": career_phase,
            "active_dasha": active_lord, "peak_career_dasha": peak_lord,
            "confidence": fi.get("confidence", ""),
        },
        "final_identity": fi,
        "macro_clusters": macro_clusters,
        "education_routes": report.get("education_routes", []),
        "demoted_fields": report.get("fields_to_avoid", []),
        "engine_gap_audit": report.get("engine_gap_audit", []),
        "parent_summary": report.get("parent_summary", ""),
        "student_summary": report.get("student_summary", ""),
        "final_recommendation": report.get("final_recommendation", ""),
    }
    section11 = f"""
      <section class="panel"><div class="section-title"><h2>11. Machine-Readable JSON</h2><span class="chip">Preserved for engine use</span></div><details><summary>View compact JSON output</summary><pre>{_esc(json.dumps(json_schema_payload, indent=2, ensure_ascii=False))}</pre></details></section>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Career Field Recommendation Report - {_esc(student_name)}</title>
<style>
  :root {{ --ink:#172033; --muted:#667085; --paper:#f5f7fb; --panel:#fff; --line:#dbe3ee; --navy:#1d3557; --teal:#0f766e; --red:#b42318; --blue:#2563eb; --shadow:0 12px 34px rgba(23,32,51,.08); }}
  * {{ box-sizing:border-box; margin:0; padding:0; }}
  body {{ font-family:"Segoe UI",Roboto,Arial,sans-serif; color:var(--ink); background:linear-gradient(180deg,rgba(29,53,87,.08),transparent 260px),var(--paper); line-height:1.52; }}
  .page {{ max-width:1540px; margin:0 auto; padding:22px; }}
  .hero {{ display:grid; grid-template-columns:minmax(360px,1.35fr) minmax(300px,.65fr); gap:18px; align-items:stretch; margin-bottom:18px; }}
  .hero-main,.hero-side,.panel {{ background:var(--panel); border:1px solid var(--line); border-radius:8px; box-shadow:var(--shadow); }}
  .hero-main {{ padding:28px; display:grid; gap:18px; }}
  .hero-side {{ padding:20px; display:grid; gap:14px; align-content:start; }}
  .eyebrow {{ color:var(--teal); font-size:.75rem; font-weight:800; letter-spacing:.11em; text-transform:uppercase; }}
  h1 {{ font-size:clamp(2rem,4vw,4.2rem); line-height:.96; letter-spacing:0; color:var(--navy); }}
  h2 {{ color:var(--navy); font-size:1.05rem; line-height:1.2; }}
  h3 {{ color:#26344d; font-size:.96rem; margin-bottom:8px; }}
  .hero-copy {{ max-width:920px; color:#344054; font-size:1.05rem; }}
  .meta-row,.pill-wrap {{ display:flex; flex-wrap:wrap; gap:8px; }}
  .chip {{ display:inline-flex; align-items:center; min-height:30px; padding:5px 10px; border-radius:999px; border:1px solid var(--line); background:#f8fafc; color:#344054; font-size:.82rem; font-weight:650; }}
  .chip.strong {{ background:#ecfdf3; color:#166534; border-color:#bbf7d0; }}
  .chip.warn {{ background:#fffbeb; color:#92400e; border-color:#fde68a; }}
  .chip.blue {{ background:#eff6ff; color:#1d4ed8; border-color:#bfdbfe; }}
  .metric-grid {{ display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:10px; }}
  .metric {{ border:1px solid var(--line); border-radius:8px; padding:12px; background:#fbfcfe; }}
  .metric b {{ display:block; color:var(--navy); font-size:1.4rem; line-height:1; }}
  .metric span {{ display:block; color:var(--muted); font-size:.76rem; margin-top:6px; }}
  .layout {{ display:grid; grid-template-columns:320px minmax(0,1fr); gap:18px; align-items:start; }}
  .rail {{ position:sticky; top:16px; display:grid; gap:14px; }}
  .panel {{ padding:18px; margin-bottom:18px; }}
  .rail .panel {{ margin-bottom:0; }}
  .section-title {{ display:flex; align-items:center; justify-content:space-between; gap:12px; margin-bottom:14px; }}
  .note {{ color:var(--muted); font-size:.9rem; }}
  .callout {{ border-left:4px solid var(--teal); background:#f0fdfa; border-radius:0 8px 8px 0; padding:12px 14px; color:#134e4a; }}
  .verdict {{ display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:12px; }}
  .verdict-card,.route,.field-card,.timebox,.audit-card {{ border:1px solid var(--line); border-radius:8px; background:#fff; }}
  .verdict-card {{ padding:14px; min-height:118px; }}
  .label {{ color:var(--muted); font-size:.72rem; font-weight:800; letter-spacing:.08em; text-transform:uppercase; margin-bottom:8px; }}
  .value {{ font-weight:800; color:var(--navy); font-size:1.02rem; }}
  .score-list {{ display:grid; gap:10px; }}
  .score-row {{ display:grid; grid-template-columns:34px minmax(180px,1fr) 96px; gap:10px; align-items:center; }}
  .rank {{ width:30px; height:30px; display:grid; place-items:center; border-radius:50%; background:var(--navy); color:#fff; font-weight:800; font-size:.82rem; }}
  .bar {{ height:10px; border-radius:999px; overflow:hidden; background:#e5eaf2; margin-top:5px; }}
  .bar span {{ display:block; height:100%; border-radius:999px; background:linear-gradient(90deg,var(--teal),var(--blue)); }}
  .score-name {{ font-weight:750; font-size:.9rem; }}
  .score-num {{ text-align:right; font-weight:800; color:var(--teal); }}
  .two-col {{ display:grid; grid-template-columns:1fr 1fr; gap:14px; }}
  .three-col {{ display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:14px; }}
  .route {{ overflow:hidden; }}
  .route-head {{ padding:14px; background:#f8fafc; border-bottom:1px solid var(--line); }}
  .route-head small {{ color:var(--teal); font-weight:800; text-transform:uppercase; letter-spacing:.07em; }}
  .route-body {{ padding:14px; display:grid; gap:10px; }}
  .pill {{ display:inline-flex; padding:4px 8px; border-radius:6px; background:#f1f5f9; border:1px solid #e2e8f0; color:#334155; font-size:.8rem; font-weight:650; }}
  .pill.primary {{ background:#ecfdf3; color:#166534; border-color:#bbf7d0; }}
  .pill.alt {{ background:#eff6ff; color:#1d4ed8; border-color:#bfdbfe; }}
  .pill.avoid {{ background:#fef3f2; color:var(--red); border-color:#fecaca; }}
  .field-grid {{ display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:10px; }}
  .field-card {{ padding:12px; display:grid; gap:8px; min-height:150px; }}
  .field-top {{ display:flex; justify-content:space-between; gap:8px; align-items:start; }}
  .field-title {{ font-weight:800; color:#26344d; line-height:1.25; }}
  .field-score {{ color:var(--teal); font-weight:900; white-space:nowrap; }}
  .level {{ width:fit-content; border-radius:999px; padding:3px 8px; font-size:.72rem; font-weight:800; border:1px solid var(--line); color:#344054; background:#f8fafc; }}
  .level.primary {{ color:#166534; background:#ecfdf3; border-color:#bbf7d0; }}
  .level.strong {{ color:#1d4ed8; background:#eff6ff; border-color:#bfdbfe; }}
  .level.backup {{ color:#92400e; background:#fffbeb; border-color:#fde68a; }}
  .level.explore {{ color:#475467; background:#f2f4f7; border-color:#eaecf0; }}
  .field-card p {{ color:var(--muted); font-size:.82rem; }}
  .matrix {{ width:100%; border-collapse:collapse; overflow:hidden; border-radius:8px; border:1px solid var(--line); }}
  .matrix th {{ text-align:left; background:var(--navy); color:#fff; padding:9px 10px; font-size:.74rem; text-transform:uppercase; letter-spacing:.06em; }}
  .matrix td {{ padding:10px; border-top:1px solid var(--line); vertical-align:top; font-size:.86rem; }}
  .matrix tr:nth-child(even) td {{ background:#fbfcfe; }}
  .timeline {{ display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:10px; }}
  .timebox,.audit-card {{ padding:12px; background:#fbfcfe; }}
  .timebox b,.audit-card b {{ color:var(--navy); display:block; margin-bottom:5px; }}
  .timebox p,.audit-card p {{ color:var(--muted); font-size:.84rem; margin-top:5px; }}
  .audit-grid {{ display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:12px; }}
  .sbc-canvas,.method-canvas {{ margin-top:12px; border:1px solid var(--line); border-radius:8px; background:#fbfcfe; padding:14px; display:grid; gap:12px; }}
  .sbc-head {{ display:flex; justify-content:space-between; align-items:flex-start; gap:12px; }}
  .sbc-head small {{ color:var(--teal); font-weight:800; text-transform:uppercase; letter-spacing:.07em; }}
  .sbc-bars {{ display:grid; gap:9px; }}
  .sbc-row {{ display:grid; grid-template-columns:38px minmax(0,1fr) 64px 82px; gap:10px; align-items:center; }}
  .sbc-rank {{ width:30px; height:30px; display:grid; place-items:center; border-radius:50%; background:#eff6ff; color:#1d4ed8; font-weight:900; font-size:.78rem; }}
  .sbc-label {{ font-size:.84rem; font-weight:800; color:#26344d; margin-bottom:4px; }}
  .sbc-track {{ height:12px; border-radius:999px; background:#e5eaf2; overflow:hidden; }}
  .sbc-track span {{ display:block; height:100%; border-radius:999px; background:linear-gradient(90deg,#6d28d9,var(--teal)); }}
  .sbc-pct {{ text-align:right; color:#6d28d9; font-weight:900; font-size:.88rem; }}
  .sbc-band {{ justify-self:end; border:1px solid #dbe3ee; background:#fff; color:#475467; border-radius:999px; padding:3px 8px; font-size:.72rem; font-weight:800; }}
  .method-grid {{ display:grid; gap:10px; }}
  .method-card {{ border:1px solid var(--line); border-radius:8px; background:#fff; padding:11px; display:grid; gap:8px; }}
  .method-title {{ display:flex; gap:8px; align-items:flex-start; color:#26344d; font-weight:900; font-size:.86rem; line-height:1.25; }}
  .method-title span {{ color:var(--teal); flex-shrink:0; }}
  .method-bars {{ display:grid; gap:6px; }}
  .method-bar-row {{ display:grid; grid-template-columns:76px minmax(0,1fr) 54px; gap:8px; align-items:center; }}
  .method-name {{ color:#475467; font-size:.75rem; font-weight:800; }}
  .method-track {{ height:9px; border-radius:999px; background:#e5eaf2; overflow:hidden; }}
  .method-track span {{ display:block; height:100%; border-radius:999px; background:linear-gradient(90deg,var(--blue),var(--teal)); }}
  .method-pct {{ text-align:right; color:var(--navy); font-weight:900; font-size:.78rem; }}
  details {{ border:1px solid var(--line); border-radius:8px; background:#fff; overflow:hidden; }}
  summary {{ cursor:pointer; padding:12px 14px; font-weight:800; color:var(--navy); background:#f8fafc; }}
  pre {{ padding:14px; overflow:auto; background:#0b1020; color:#dbe4ff; font-size:.78rem; line-height:1.45; }}
  .small-list {{ display:grid; gap:8px; color:#344054; font-size:.9rem; }}
  .small-list b {{ color:var(--navy); }}
  .footer-note {{ color:var(--muted); font-size:.8rem; text-align:center; padding:8px 0 24px; }}
  @media (max-width:1180px) {{ .layout,.hero {{ grid-template-columns:1fr; }} .rail {{ position:static; }} .field-grid {{ grid-template-columns:repeat(2,minmax(0,1fr)); }} .verdict,.timeline {{ grid-template-columns:repeat(2,minmax(0,1fr)); }} }}
  @media (max-width:760px) {{ .page {{ padding:12px; }} .hero-main,.hero-side,.panel {{ padding:14px; }} .two-col,.three-col,.field-grid,.verdict,.timeline,.audit-grid,.metric-grid {{ grid-template-columns:1fr; }} .score-row {{ grid-template-columns:30px 1fr 70px; }} .sbc-row {{ grid-template-columns:32px 1fr 58px; }} .sbc-band {{ display:none; }} }}
  @media print {{ body {{ background:#fff; }} .page {{ max-width:none; padding:0; }} .hero-main,.hero-side,.panel {{ box-shadow:none; break-inside:avoid; }} .rail {{ position:static; }} }}
</style>
</head>
<body>
<div class="page">
  {hero_html}
  <div class="layout">
    {rail_html}
    <main>
      {section1}
      {section2}
      {section3}
      {section4}
      {section5}
      {section6}
      {section7}
      {section8}
      {section9}
      {section10}
      {section11}
    </main>
  </div>
  <p class="footer-note">JyotishAI Career Engine {_esc(ENGINE_VERSION)} &bull; Generated {gen_date}</p>
</div>
</body>
</html>"""
    return html


def render_report_html(
    student_name: str,
    career_phase: str,
    active_lord: str,
    peak_lord: str,
    top35: List[Dict],
    macro_clusters: List[Dict],
    report: Dict,
    chart_facts: Optional[Dict[str, Any]] = None,
) -> str:
    """Canonical dashboard HTML for all career-field report outputs."""
    gen_date = datetime.now().strftime("%d %b %Y, %H:%M")
    fi = report.get("final_identity", {}) or {}
    snap = report.get("snapshot", {}) or {}
    chart_facts = chart_facts or {}

    def score_value(row: Dict) -> float:
        return round(float((row or {}).get("final_score", 0.0) or 0.0), 2)

    def score_text(row: Dict) -> str:
        return f"{score_value(row):.2f}"

    def score_width(row: Dict) -> float:
        return max(0.0, min(100.0, score_value(row)))

    def level_class(level: str) -> str:
        l = (level or "").lower()
        if "primary" in l:
            return "primary"
        if "strong" in l or "special" in l:
            return "strong"
        if "backup" in l or "pg" in l:
            return "backup"
        return "explore"

    def split_options(text: Any) -> List[str]:
        raw = str(text or "").replace(";", ",")
        return [p.strip() for p in raw.split(",") if p.strip()]

    def pills(items: List[str], cls: str = "") -> str:
        klass = f"pill {cls}".strip()
        return "".join(f'<span class="{klass}">{_esc(i)}</span>' for i in items if str(i or "").strip())

    top1 = top35[0] if top35 else {}
    top2 = top35[1] if len(top35) > 1 else {}
    top3 = top35[2] if len(top35) > 2 else {}
    top1_label = _field_display_name(top1) if top1 else (snap.get("best_ug_route") or "Undetermined")
    top2_label = _field_display_name(top2) if top2 else (snap.get("strong_backup_route") or "")
    top3_label = _field_display_name(top3) if top3 else (snap.get("best_pg_route") or "")
    top_cluster = macro_clusters[0] if macro_clusters else {"cluster": fi.get("macro_identity", ""), "strength_pct": 0}
    field_llm = {f.get("field"): f for f in report.get("top_20_fields", [])}
    interp_map = {i.get("cluster"): i.get("interpretation", "") for i in report.get("macro_cluster_interpretations", [])}

    # Section 3 — astrological signature
    sig_rows = [
        [_esc(r.get("factor", "")), _esc(r.get("observation", "")), _esc(r.get("career_meaning", ""))]
        for r in report.get("astrological_signature", [])
    ]
    section3 = _table(["Astrological Factor", "Observation", "Career Meaning"], sig_rows)

    # Section 4 — macro cluster ranking
    mc_rows = [
        [str(c["rank"]), _esc(c["cluster"]), f"{c['strength_pct']:.0f}%", _esc(interp_map.get(c["cluster"], ""))]
        for c in macro_clusters
    ]
    section4 = _table(["Rank", "Macro Cluster", "Strength", "Interpretation"], mc_rows)

    # Section 5 — top 20 fields (engine score + rank are deterministic; recommended_level/reason from LLM)
    top20_rows = []
    for rank, r in enumerate(top35[:20], 1):
        label = _field_display_name(r)
        llm_f = field_llm.get(label, {})
        score = round(float(r.get("final_score", 0.0) or 0.0), 1)
        top20_rows.append([
            str(rank), _esc(label), f"{score:.1f}%",
            _esc(llm_f.get("recommended_level", "Explore")),
            _esc(llm_f.get("reason", "")),
        ])
    section5 = _table(["Rank", "Field", "Fit", "Recommended Level", "Reason"], top20_rows)

    # Section 6 — education routes
    route_blocks = []
    for route in report.get("education_routes", []):
        rows = [
            ["UG", _esc(route.get("ug_options", ""))],
            ["PG", _esc(route.get("pg_options", ""))],
            ["PhD", _esc(route.get("phd_options", ""))],
            ["Careers", _esc(route.get("careers", ""))],
            ["Best for", _esc(route.get("best_for", ""))],
            ["Risk level", _esc(route.get("risk_level", ""))],
            ["Long-term value", _esc(route.get("long_term_value", ""))],
        ]
        route_blocks.append(
            f"<h3>{_esc(route.get('route_name',''))}</h3>"
            f"<h4>{_esc(route.get('title',''))}</h4>"
            + _table(["Stage", "Recommended Options"], rows)
        )
    section6 = "".join(route_blocks)

    # Section 7 — fields to avoid
    avoid_rows = [
        [_esc(a.get("field", "")), _esc(a.get("status", "")), _esc(a.get("reason", ""))]
        for a in report.get("fields_to_avoid", [])
    ]
    section7 = _table(["Field", "Status", "Reason"], avoid_rows) if avoid_rows else "<p><em>No fields flagged for demotion.</em></p>"

    # Section 8 — engine output comparison
    comp_rows = [
        [str(c.get("engine_rank", "")), _esc(c.get("engine_field", "")), _esc(c.get("correct_status", "")), _esc(c.get("action", ""))]
        for c in report.get("engine_output_comparison", [])
    ]
    section8 = _table(["Engine Rank", "Engine Field", "Correct Status", "Action"], comp_rows)

    # Section 9 — engine gap diagnosis
    gap_rows = [
        [str(g.get("gap_no", "")), _esc(g.get("gap", "")), _esc(g.get("effect", "")), _esc(g.get("fix", ""))]
        for g in report.get("engine_gap_audit", [])
    ]
    section9 = _table(["Gap No.", "Gap", "Effect", "Fix"], gap_rows)

    # JSON schema payload for machine consumption (section 13)
    json_schema_payload = {
        "student_profile": {
            "name": student_name, "career_phase": career_phase,
            "active_dasha": active_lord, "peak_career_dasha": peak_lord,
            "confidence": fi.get("confidence", ""),
        },
        "final_identity": fi,
        "macro_clusters": macro_clusters,
        "top_20_fields": top20_rows,
        "education_routes": report.get("education_routes", []),
        "demoted_fields": report.get("fields_to_avoid", []),
        "engine_gap_audit": report.get("engine_gap_audit", []),
        "parent_summary": report.get("parent_summary", ""),
        "student_summary": report.get("student_summary", ""),
        "final_recommendation": report.get("final_recommendation", ""),
    }

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Career Field Recommendation Report - {_esc(student_name)}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #f4f6f9; color: #222; line-height: 1.6; }}
  header {{ background: linear-gradient(135deg, #1a237e 0%, #4a148c 100%); color: #fff; padding: 26px 40px; }}
  header h1 {{ font-size: 1.55rem; letter-spacing: 0.02em; }}
  header p {{ margin-top: 6px; opacity: 0.88; font-size: 0.9rem; }}
  main {{ max-width: 1080px; margin: 0 auto; padding: 30px 24px 60px; }}
  section {{ background: #fff; border-radius: 10px; box-shadow: 0 1px 6px rgba(0,0,0,0.08); padding: 24px 28px; margin-bottom: 26px; }}
  h2.sec-title {{ color: #1a237e; font-size: 1.15rem; border-bottom: 2px solid #e3e6f5; padding-bottom: 10px; margin-bottom: 16px; }}
  h3 {{ color: #4a148c; font-size: 1.02rem; margin: 18px 0 6px; }}
  h4 {{ color: #333; font-size: 0.95rem; margin-bottom: 8px; }}
  table {{ width: 100%; border-collapse: collapse; margin: 10px 0 18px; }}
  th {{ background: #1a237e; color: #fff; text-align: left; padding: 9px 12px; font-size: 0.78rem; text-transform: uppercase; letter-spacing: 0.04em; }}
  td {{ padding: 9px 12px; border-bottom: 1px solid #e8e8e8; font-size: 0.88rem; vertical-align: top; }}
  tr:nth-child(even) td {{ background: #f8f9fd; }}
  .identity-box {{ background: linear-gradient(135deg,#eef1fb,#f7edfb); border-left: 4px solid #4a148c; padding: 16px 20px; border-radius: 6px; margin: 10px 0; }}
  .identity-box p {{ margin: 4px 0; }}
  blockquote {{ border-left: 4px solid #1a237e; margin: 12px 0; padding: 10px 18px; background: #f6f7fc; font-style: italic; }}
  .llm-tag {{ display:inline-block; font-size:0.68rem; font-weight:700; color:#fff; background:#6a1b9a; border-radius:4px; padding:2px 7px; margin-left:8px; vertical-align:middle; }}
  .badge {{ display:inline-block; padding:2px 8px; border-radius:10px; font-size:0.78rem; font-weight:600; background:#e3e6f5; color:#1a237e; }}
  details {{ margin-top: 14px; border: 1px solid #dfe3ec; border-radius: 6px; }}
  summary {{ cursor: pointer; padding: 8px 12px; font-weight: 700; color: #1a237e; }}
  pre {{ margin:0; padding: 12px; background:#0b1020; color:#dbe4ff; font-size:0.76rem; overflow-x:auto; border-radius:0 0 6px 6px; }}
</style>
</head>
<body>
<header>
  <h1>Career Field Recommendation Report</h1>
  <p>Student: <strong>{_esc(student_name)}</strong> &bull; Generated: {gen_date} &bull; Engine: {ENGINE_VERSION}</p>
</header>
<main>

<section id="s1">
  <h2 class="sec-title">1. Executive Summary</h2>
  <p><strong>Name:</strong> {_esc(student_name)}</p>
  <p><strong>Career phase:</strong> {_esc(career_phase)}</p>
  <p><strong>Active Mahadasha:</strong> {_esc(active_lord)}</p>
  <p><strong>Peak Career Mahadasha:</strong> {_esc(peak_lord)}</p>
  <p><strong>Final Career Identity:</strong><span class="llm-tag">LLM</span></p>
  <blockquote>{_esc(fi.get('macro_identity',''))}</blockquote>
  <p><strong>Best education direction:</strong><span class="llm-tag">LLM</span></p>
  <blockquote>{_esc(fi.get('one_line_summary',''))}</blockquote>
  <p><strong>Confidence level:</strong> <span class="badge">{_esc(fi.get('confidence',''))}</span></p>
</section>

<section id="s2">
  <h2 class="sec-title">2. Final Recommendation Snapshot <span class="llm-tag">LLM</span></h2>
  {_table(["Priority", "Recommendation"], [
      ["Best UG route", _esc(top1_label)],
      ["Best PG route", _esc(top3_label)],
      ["Best career cluster", _esc(top_cluster.get("cluster", ""))],
      ["Strong backup route", _esc(top2_label)],
      ["Avoid as primary", _esc(snap.get("avoid_as_primary",""))],
      ["Best working style", _esc(snap.get("best_working_style",""))],
  ])}
</section>

<section id="s3">
  <h2 class="sec-title">3. Astrological Career Signature <span class="llm-tag">LLM</span></h2>
  <p>This section explains <em>why</em> the chart points to the recommended fields.</p>
  {section3}
</section>

<section id="s4">
  <h2 class="sec-title">4. Final Macro-Cluster Ranking <span class="badge">Engine (deterministic)</span> + <span class="llm-tag">LLM interpretation</span></h2>
  {section4}
  <p><em>Rule: a field should not enter the final top 10 unless its parent macro-cluster is also strong.</em></p>
</section>

<section id="s5">
  <h2 class="sec-title">5. Corrected Top 20 Fields <span class="badge">Engine scores/ranks</span> + <span class="llm-tag">LLM level/reason</span></h2>
  {section5}
</section>

<section id="s6">
  <h2 class="sec-title">6. Education Route Mapping <span class="llm-tag">LLM</span></h2>
  {section6}
</section>

<section id="s7">
  <h2 class="sec-title">7. Fields to Avoid as Primary <span class="llm-tag">LLM</span></h2>
  {section7}
</section>

<section id="s8">
  <h2 class="sec-title">8. Engine Output Comparison <span class="llm-tag">LLM audit of engine ranks</span></h2>
  {section8}
</section>

<section id="s9">
  <h2 class="sec-title">9. Engine Gap Diagnosis <span class="llm-tag">LLM</span></h2>
  {section9}
</section>

<section id="s10">
  <h2 class="sec-title">10. Final Student-Friendly Recommendation <span class="llm-tag">LLM</span></h2>
  <blockquote>{_esc(report.get('final_recommendation',''))}</blockquote>
</section>

<section id="s11">
  <h2 class="sec-title">11. Parent Report Version <span class="llm-tag">LLM</span></h2>
  <div class="identity-box"><p>{_esc(report.get('parent_summary',''))}</p></div>
</section>

<section id="s12">
  <h2 class="sec-title">12. Student Version <span class="llm-tag">LLM</span></h2>
  <div class="identity-box"><p>{_esc(report.get('student_summary',''))}</p></div>
</section>

<section id="s13">
  <h2 class="sec-title">13. Recommended JSON Output Schema</h2>
  <details>
    <summary>View machine-readable JSON (engine scores + LLM narrative)</summary>
    <pre>{_esc(json.dumps(json_schema_payload, indent=2, ensure_ascii=False))}</pre>
  </details>
</section>

</main>
</body>
</html>"""
    return html


def _build_career_field_report_bundle(
    data: Dict[str, Any],
    student_name: Optional[str] = None,
    use_new_renderer: bool = True,
) -> Dict[str, Any]:
    """Run engine + SBC + LLM narrative and render the career field report HTML."""
    payload = parse_json_payload(data)
    name = student_name or getattr(payload, "name", "Unknown")

    logger.info("[career_field_report_v2] Running engine for %s...", name)
    results = run_engine(payload)

    try:
        from .sbc import SarvatobhadraEngine
        results = SarvatobhadraEngine(payload).apply_to_ranking(results)
    except Exception as sbc_err:
        logger.warning("[career_field_report_v2] SBC advisory layer unavailable: %s", sbc_err)

    current_age = float(getattr(payload, "current_age", 0) or 0)
    active_lord = _get_active_dasha_lord(getattr(payload, "dasha_sequence", []), current_age)
    peak_lord = getattr(payload, "peak_dasha_lord", "") or active_lord
    age_stage = classify_age_stage(current_age, results)
    career_phase_raw = _resolve_career_phase(payload)
    career_phase = _career_phase_label(age_stage, career_phase_raw)
    chart_facts = _build_chart_signature_facts(payload, active_lord, peak_lord)
    macro_clusters = _macro_cluster_ranking(results, top_n=20)

    report = _call_llm_for_report(name, career_phase, active_lord, peak_lord, chart_facts, results, macro_clusters)
    if not report:
        logger.warning(
            "[career_field_report_v2] LLM report generation failed/unavailable — using deterministic fallback."
        )
        report = _fallback_report_json(results, macro_clusters, name)

    html = None
    if use_new_renderer:
        _timeline_periods = getattr(payload, "career_timeline", None)
        if _timeline_periods:
            try:
                from .report_renderer import render_career_report
                _raw_view = {
                    "context": {
                        "employment_status": getattr(payload, "employment_status", ""),
                        "designation": name,
                    },
                    "chart": chart_facts or {},
                    "periods": _timeline_periods,
                }
                html = render_career_report(_raw_view)
                logger.info("[career_field_report_v2] Rendered with new report_renderer (Jinja2) path.")
            except Exception as new_render_err:
                logger.warning(
                    "[career_field_report_v2] New renderer failed (%s) — falling back to legacy render_report_html.",
                    new_render_err,
                )
                html = None
        else:
            logger.info(
                "[career_field_report_v2] No timeline periods on payload — using legacy renderer "
                "(new renderer targets timeline-period reports; the 14-section field-ranking "
                "report has no period-level view model to build)."
            )

    if html is None:
        try:
            html = render_report_html_rich(name, career_phase, active_lord, peak_lord, results, macro_clusters, report, chart_facts)
        except Exception as _rich_err:
            logger.warning(
                "[career_field_report_v2] Rich field-report renderer failed (%s) — "
                "falling back to plain sec-title renderer.", _rich_err
            )
            html = render_report_html(name, career_phase, active_lord, peak_lord, results, macro_clusters, report, chart_facts)

    return {
        "student_name": name,
        "career_phase": career_phase,
        "active_lord": active_lord,
        "peak_lord": peak_lord,
        "results": results,
        "macro_clusters": macro_clusters,
        "report": report,
        "chart_facts": chart_facts,
        "html": html,
        "payload": payload,
    }


def build_career_field_report_from_chart(
    chart: Dict[str, Any],
    student_name: Optional[str] = None,
) -> Dict[str, Any]:
    """Build the career field report from consolidated chart JSON (API / web use)."""
    return _build_career_field_report_bundle(chart, student_name=student_name)


def generate_career_field_report_v2(
    chart_path: str,
    student_name: Optional[str] = None,
    output_dir: str = "educational_records",
    enable_llm_field_explanations: bool = False,
    use_new_renderer: bool = True,
) -> str:
    """Run the engine on a chart JSON file and write the 14-section
    Career Field Recommendation Report as a standalone HTML file.

    Parameters
    ----------
    chart_path : path to a JyotishAI chart JSON (same format as export_field_summaries.py)
    student_name : override name; falls back to the payload's own `name` field
    output_dir : directory to write the HTML report to
    enable_llm_field_explanations : if True, also runs the engine's own
        per-field LLM explanation pass (slower, extra LLM calls) — the new
        report format does not require this since it does its own narrative
        pass, so default is False.

    use_new_renderer : if True (default), attempt the new Jinja2-templated
        renderer (jyotish/report_renderer.py, Phase 4 of the 2026-07 career
        report refactor) when the payload carries timeline period data
        (payload.career_timeline). Falls back to the legacy render_report_html
        renderer automatically if no timeline periods are present, or if the
        new renderer raises for any reason — the legacy path is always the
        safety net and is never removed.

    Returns
    -------
    The path to the written HTML file.
    """
    with open(chart_path, "r", encoding="utf-8") as fh:
        data = json.load(fh)

    bundle = _build_career_field_report_bundle(
        data,
        student_name=student_name,
        use_new_renderer=use_new_renderer,
    )
    html = bundle["html"]
    name = bundle["student_name"]

    os.makedirs(output_dir, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = name.lower().replace(" ", "_")
    out_path = os.path.join(output_dir, f"career_field_report_{safe_name}_{ts}.html")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(html)

    logger.info("[career_field_report_v2] Wrote report -> %s", out_path)
    return out_path
