"""
career_validation_prompt.py  —  JyotishAI Career Journey Validator  v1.0
=========================================================================

PURPOSE
-------
Provides the LLM prompt infrastructure to validate the career journey predictions
generated by the JyotishAI Career Timeline Engine (jyotish/timeline.py).

Given:
  • A natal chart (NatalPayloadV2 or equivalent dict)
  • Engine-predicted career timeline (list of AD blocks with event_type, scores,
    enhancer deltas, yoga flags, KP scores, transit flags, etc.)
  • Actual career history supplied by the user (list of real events with dates,
    companies, roles, and self-assessed intensity)

The validator:
  1. Matches each actual career event to the nearest predicted block (±9 months window).
  2. Scores the match quality on five sub-dimensions: Dasha, Yoga, KP, Transit, Enhancer.
  3. Identifies "misses" — predicted high-score events that produced no career change.
  4. Identifies "gaps" — actual events the engine failed to predict.
  5. Computes an overall Prediction Accuracy Index (PAI) with confidence bounds.
  6. Attributes predictive power to individual astrological factors, ranking them by
     information gain.
  7. Produces a concrete improvement plan for the engine's scoring weights.

ARCHITECTURE  (mirrors field_deterministic_engine_v1_llm.py / jyotish/llm.py)
-----------
• Step 1 — VALIDATOR:   Deep analytical pass. Matches events, scores predictions,
                         extracts factor attributions. Returns structured JSON.
• Step 2 — NARRATOR:    Synthesises Step 1 findings into a prose report and
                         improvement recommendations.

PUBLIC API
----------
  build_validator_user_message(chart_summary, predicted_blocks, actual_history)
      → (str, str)   # (step1_system_prompt, step1_user_message)

  build_narrator_user_message(chart_summary, validation_result)
      → (str, str)   # (step2_system_prompt, step2_user_message)

  call_validation_llm(chart_summary, predicted_blocks, actual_history, ...)
      → ValidationResult

  parse_validation_response(raw_json) → dict

  generate_validation_html(validation_result, payload, output_dir) → str
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass, field as dc_field
from datetime import date
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# ENGINE VERSION
# ---------------------------------------------------------------------------
VALIDATOR_VERSION = "career_validator_v1.1"  # bumped to invalidate stale pyc

# ---------------------------------------------------------------------------
# Gap-audit fix (2026-08): sanitizer for the one place in this file (and,
# per the wider audit, in the whole jyotish/ LLM-integration layer) where
# genuine free-text *user* input -- career-event description/role/company/
# notes, supplied via extract_actual_history_from_payload() or a direct API
# caller -- is interpolated into an LLM prompt. Every other prompt in this
# module is built from server-controlled structured data (scores, dates,
# chart facts), which is why this is the actual injection-risk surface, not
# those. This does not attempt full prompt-injection defense (an LLM can
# still be influenced by adversarial *content*, which no string filter can
# fully prevent) -- it specifically closes the two concrete, testable risks:
# (1) embedded newlines/control chars forging a fake "[Axx] ... ━━━" section
# boundary that could desynchronize the validator's structured event index,
# and (2) unbounded length pushing other prompt content out of context.
# ---------------------------------------------------------------------------
_USER_TEXT_MAX_LEN = 300


def _sanitize_user_text(value: Any, max_len: int = _USER_TEXT_MAX_LEN) -> str:
    """Collapse newlines/control chars and cap length on untrusted text
    before it is embedded into an LLM prompt. Non-string input is coerced
    via str(); None/empty returns "".
    """
    if value is None:
        return ""
    text = str(value)
    # Collapse all whitespace runs (including newlines/tabs/CR) to a single
    # space so multi-line input can't forge a new prompt line/section.
    text = " ".join(text.split())
    # Strip any remaining non-printable/control characters defensively.
    text = "".join(ch for ch in text if ch.isprintable() or ch == " ")
    if len(text) > max_len:
        text = text[: max_len - 1].rstrip() + "…"
    return text

# ---------------------------------------------------------------------------
# D10 DEVATA DIAGNOSTIC LABELS
# ---------------------------------------------------------------------------
_D10_ARCHETYPE_LABEL = {
    "unemployed":        "🔴 UNEMPLOYED — Can't find work",
    "salary_stagnant":   "🟡 SALARY STAGNANT — Effort not rewarded",
    "promotion_blocked": "🟠 PROMOTION BLOCKED — Recognition leaks away",
    "sudden_halt":       "🔴 SUDDEN HALT — Layoff / career ruin",
}
_D10_ARCHETYPE_BODY = {
    "unemployed": (
        "The devata of the 4th lord from Sun in D10 holds the key. "
        "Sun = soul's authority. 4th from it = career foundation. "
        "When this devata is unworshipped, the ground keeps shifting."
    ),
    "salary_stagnant": (
        "The devata of the 10th lord from Mercury in D10 is silent. "
        "Mercury = exchange — what you give, what you receive. "
        "When ignored, effort gets recognised but never rewarded."
    ),
    "promotion_blocked": (
        "10th lord from Jupiter in D10. Jupiter = expansion and rightful recognition. "
        "When this devata is weak, growth leaks out of your hands — into someone else's."
    ),
    "sudden_halt": (
        "8th lord from D10 Lagna. This devata doesn't warn you — it just stops everything. "
        "One wrong transit. One unseen enemy. One restructuring."
    ),
}

def _build_d10_devata_lines(d10_dd: Any) -> List[str]:
    """Format d10_devata_diagnostics dict into prompt lines."""
    if not d10_dd or not isinstance(d10_dd, dict):
        return ["  D10 devata data: not available"]
    lines: List[str] = []
    for key in ("unemployed", "salary_stagnant", "promotion_blocked", "sudden_halt"):
        entry = d10_dd.get(key)
        if not entry:
            continue
        label   = _D10_ARCHETYPE_LABEL.get(key, key.upper())
        body    = _D10_ARCHETYPE_BODY.get(key, "")
        lord    = entry.get("key_lord", "?")
        devata  = entry.get("devata", "?")
        sign    = entry.get("key_sign", "?")
        pivot   = entry.get("pivot_planet", "?")
        pivot_s = entry.get("pivot_sign_d10", "?")
        lines += [
            f"  {label}",
            f"    Pivot: {pivot} in {pivot_s} (D10)  →  {key.replace('_',' ').title()} house: {sign}  →  Lord: {lord}  →  Devata: {devata}",
            f"    {body}",
            "",
        ]
    return lines or ["  D10 devata data: not available"]

# ---------------------------------------------------------------------------
# TIME-WINDOW TOLERANCE (months)
# ---------------------------------------------------------------------------
_HIT_WINDOW_MONTHS     = 9   # ±9 months → confirmed match (DIRECT HIT)
_NEAR_HIT_WINDOW_MONTHS = 18  # ±18 months → near-miss / partial credit

# ---------------------------------------------------------------------------
# EVENT TYPE CANONICAL NAMES  (must match _classify_event in timeline.py)
# ---------------------------------------------------------------------------
_ALL_EVENT_TYPES = [
    "PROMOTION", "SALARY_HIKE", "JOB_CHANGE", "BREAKTHROUGH",
    "INCOME_INFLECTION", "LEADERSHIP_EXPANSION", "AUTHORITY_SHIFT",
    "RISK_PERIOD", "CALIBRATION", "STABILITY",
    "ENTREPRENEURSHIP_WINDOW", "EQUITY_EVENT", "LATERAL_MOVE", "SANDHI_PERIOD",
]

# ---------------------------------------------------------------------------
# ASTROLOGICAL FACTOR IDs  (for attribution analysis)
# ---------------------------------------------------------------------------
_FACTOR_IDS = [
    # Core dasha
    "MD_AD_STRENGTH", "KP_CUSP_SUBLORD", "JAIMINI_CHARA",
    # Yoga factors
    "YOGA_RAJAYOGA", "YOGA_GAJAKESARI", "YOGA_NEECHA_BHANGA", "YOGA_VIPARITA_RY",
    "YOGA_MAHAPURUSHA", "YOGA_ADHI", "YOGA_DHANA",
    # Enhancer G1-G9
    "G1_COMBUSTION", "G2_RETROGRADE", "G3_GRAHA_YUDDHA",
    "G4_DIG_BALA", "G5_NEECHA_BHANGA", "G6_VIPARITA_RY",
    "G7_PAPA_KARTARI", "G8_KALA_SARPA", "G9_UPACHAYA",
    # Enhancer G10-G14 (timing)
    "G10_SOOKSHAM", "G11_SANDHI", "G12_NAKSHATRA_TRIGGER",
    "G13_PAV_TRANSIT", "G14_KAKSHA",
    # Enhancer G15-G17 (dasha systems)
    "G15_JAIMINI_CHARA_DASHA", "G16_YOGINI_DASHA", "G17_ASHTOTTARI",
    # Enhancer G18-G24 (divisional + lagna)
    "G18_D10_FULL", "G19_D60", "G20_D27", "G21_VIMSOPAKA",
    "G22_SURYA_LAGNA", "G23_ARUDHA", "G24_KARAKAMSHA",
    # Enhancer G25-G27 (KP precision)
    "G25_KP_SSL", "G26_KP_RULING_PLANETS", "G27_KP_CHAIN",
    # Enhancer G28-G31 (event classification)
    "G28_ENTREPRENEURSHIP", "G29_EQUITY", "G30_LATERAL_MOVE", "G31_DASHA_CHIDRA",
    # Enhancer G32-G34 (aspects)
    "G32_MARS_ASPECT", "G33_NATAL_ASPECTS", "G34_TRANSIT_ASPECTS",
    # Macro
    "MACRO_SECTOR_INDEX",
]

# =============================================================================
# STEP 1 — VALIDATOR SYSTEM PROMPT
# =============================================================================

_VALIDATOR_SYSTEM_PROMPT = """\
You are a senior Jyotish career validation analyst and data scientist. Your task is to \
rigorously evaluate a deterministic Vedic astrology career prediction engine by comparing \
its predictions against a person's actual career history.

━━━ ROLE AND CONSTRAINTS ━━━
• You are NOT reinterpreting the chart from scratch. The engine has already run.
• You are evaluating HOW WELL each engine prediction matched reality.
• Never fabricate career events. Only work with the events explicitly provided.
• Never fabricate astrological signals. Only cite signals present in the provided data.
• If any data field is "not available" or null, skip that sub-analysis entirely.
• Maintain strict objectivity. A prediction is a HIT only if the event type AND timing align.

━━━ VALIDATION METHODOLOGY ━━━

STEP 1 — EVENT MATCHING (mandatory for every actual event)
For each actual career event in the history:
  a. Find the engine-predicted block whose date range best overlaps the actual event date.
  b. Compute the offset in months between actual_date and the predicted block's midpoint.
  c. Classify:
       DIRECT_HIT       : offset ≤ {HIT_WINDOW} months AND event_type is semantically correct
       NEAR_HIT         : offset ≤ {NEAR_HIT_WINDOW} months OR event_type is adjacent category
       MISS             : offset > {NEAR_HIT_WINDOW} months OR event_type is completely wrong
  d. For DIRECT_HIT and NEAR_HIT: identify which signals in the predicted block were activated.

EVENT TYPE ADJACENCY MAP (use for semantic correctness check):
  PROMOTION       ↔ LEADERSHIP_EXPANSION, AUTHORITY_SHIFT, BREAKTHROUGH
  JOB_CHANGE      ↔ BREAKTHROUGH, LATERAL_MOVE, ENTREPRENEURSHIP_WINDOW
  SALARY_HIKE     ↔ INCOME_INFLECTION, PROMOTION, EQUITY_EVENT
  RISK_PERIOD     ↔ SANDHI_PERIOD, CALIBRATION
  STABILITY       ↔ CALIBRATION
  LATERAL_MOVE    ↔ JOB_CHANGE, CALIBRATION
  ENTREPRENEURSHIP_WINDOW ↔ JOB_CHANGE, BREAKTHROUGH, LATERAL_MOVE

STEP 2 — PREDICTED-BUT-NOT-MANIFESTED ANALYSIS
For each predicted block with career_score ≥ 0.60 that has NO matched actual event:
  a. Identify all active astrological signals in that block.
  b. Hypothesize WHY it may not have manifested:
       - "SUPPRESSED": strong negative factors (Papa Kartari, Kala Sarpa, Sandhi) overrode
       - "DELAYED": event may have occurred slightly outside the window; flag for review
       - "INTERNAL": career change was psychological/internal but not a job-market event
       - "DATA_GAP": actual history may be incomplete for that period

STEP 3 — UNPREDICTED ACTUAL EVENTS (engine gaps)
For each actual event that had no DIRECT_HIT or NEAR_HIT match:
  a. Identify which Vimshottari dasha (MD/AD/PD) was active at that time using the
     complete dasha sequence provided above. Quote the exact MD, AD, and PD lord.
  b. Check the engine's predicted block for that dasha — what was its career_score?
  c. Identify which signals WERE present but scored too low:
       - Was the Yoga score present but underweighted?
       - Was KP convergence present but not fully captured?
       - Was the D10/D60 modifier active?
       - Were any of the 34-gap enhancer factors (G1-G34) active and high?
  d. Assign a ROOT_CAUSE label:
       "SCORE_THRESHOLD_TOO_HIGH"  : event occurred but score was 0.45-0.60 (just below cut)
       "WRONG_EVENT_TYPE"          : event happened but was classified as wrong type
       "MISSING_YOGA_SIGNAL"       : a key yoga was present but undetected by engine
       "KP_CONVERGENCE_MISSED"     : H10/H11 sub-lord convergence was present but unscored
       "TRANSIT_TRIGGER_ABSENT"    : Jupiter/Saturn transit trigger was missing from engine data
       "ENHANCER_GAP"              : one of G1-G34 would have elevated the score but was zero
       "DASHA_BOUNDARY_ISSUE"      : event occurred at MD/AD junction (Dasha Sandhi)
       "INSUFFICIENT_DATA"         : chart data was too sparse to evaluate

STEP 4 — FACTOR ATTRIBUTION ANALYSIS
For ALL matched events (DIRECT_HIT + NEAR_HIT combined):
  For each of the following factor groups, compute a contribution score 0.0-1.0:
    - MD_AD_STRENGTH:          Was the MD/AD lord strong (dignity + D9 + functional nature)?
    - KP_CUSP_SUBLORD:         Was the H10/H11 KP sub-lord the MD or AD lord?
    - JAIMINI_CHARA:           Was the Jaimini Chara Dasha score ≥ 0.65?
    - YOGA_FLAGS:              Were activated yogas present in the matched block?
    - G10_SOOKSHAM:            Did the Sooksham (4th-level) dasha precision help identify timing?
    - G12_NAKSHATRA_TRIGGER:   Was a nakshatra transit trigger flagged?
    - G13_PAV_TRANSIT:         Was the PAV transit score ≥ 0.60?
    - G16_YOGINI_DASHA:        Was a career-positive Yogini lord (Siddha/Dhanya) active?
    - G18_D10_FULL:            Was the D10 full score ≥ 0.60?
    - G21_VIMSOPAKA:           Was the Vimsopaka Bala score ≥ 0.65?
    - G25_KP_SSL:              Was the KP Sub-Sub-Lord active?
    - G34_TRANSIT_ASPECTS:     Were transit aspect flags active for the matched window?

  Then rank ALL factor IDs from most predictive (contributed to most DIRECT_HITs) to least.
  Provide a numeric importance score 0.0-1.0 for each.

STEP 5 — PREDICTION ACCURACY INDEX (PAI)
Compute:
  n_actual        = total number of actual career events
  n_direct        = events with DIRECT_HIT
  n_near          = events with NEAR_HIT
  n_miss          = events with MISS (no match at all)
  n_predicted_miss = predicted blocks (score≥0.60) with no actual event

  PAI_strict      = n_direct / n_actual                      (0.0-1.0)
  PAI_relaxed     = (n_direct + 0.5 * n_near) / n_actual    (0.0-1.0)
  precision       = n_direct / max(1, n_direct + n_predicted_miss)
  recall          = n_direct / max(1, n_actual)
  f1_score        = 2 * precision * recall / max(0.001, precision + recall)
  timing_accuracy = mean absolute offset in months across all hits (lower=better)

STEP 6 — CONFIDENCE BAND
Classify overall engine performance:
  PAI_relaxed ≥ 0.80 → "EXCELLENT"    (engine is highly calibrated for this chart)
  PAI_relaxed ≥ 0.65 → "GOOD"         (engine captures major career inflections well)
  PAI_relaxed ≥ 0.50 → "MODERATE"     (major events caught, timing imprecise)
  PAI_relaxed ≥ 0.35 → "DEVELOPING"   (structural signals present, needs calibration)
  PAI_relaxed <  0.35 → "NEEDS_WORK"  (fundamental chart data or scoring gap)

STEP 7 — ENGINE IMPROVEMENT RECOMMENDATIONS
Based on Steps 2-4, produce exactly 3-5 concrete recommendations:
  Each recommendation must:
    • Name the specific factor group (e.g., "G21_VIMSOPAKA", "KP_CUSP_SUBLORD")
    • State the observed pattern ("was HIGH in 4 of 5 hits but only weighted at 0.04")
    • Suggest the corrective action ("increase weight to 0.07 or add to primary score")
  Prioritise by information gain (factor most correlated with DIRECT_HITs goes first).

━━━ WEIGHT REFERENCE (engine's current scoring weights — calibration v5) ━━━
PRIMARY 8 sub-score weights (sum = 1.00):
  career_activation  (KP significator check):   0.20  ← trimmed 0.22→0.20 to fund KP v5 raise
  strength_product   (eff_strength product):    0.13  ← trimmed 0.15→0.13 to fund KP v5 raise
  functional_nature  (benefic/malefic nature):  0.13
  house_activation   (H10/H6/H2 activation):   0.10
  kp_cusp_score      (KP cusp sub-lord check):  0.25  ← Step 1 v5: raised 0.20→0.25
  jaimini_score      (chara karaka alignment):  0.07  ← trimmed 0.08→0.07 to fund KP v5 raise
  d10_alignment      (Dashamsha career chart):  0.07
  company_score      (AK/AmK company):          0.05

EXPLICIT YOGA PRIMARY COMPONENTS (named weights, additive — Steps 2 & 3 v5):
  yoga_rajayoga_sub  (Rajayoga active lord):    weight 0.05  ← Step 2: 1.0 if forming planet is MD/AD lord; 0.4 natal potential
  yoga_vry_sub       (Viparita RY active lord): weight 0.03  ← Step 3: Harsha/Sarala/Vimala VRY same logic

ADDITIVE BONUSES (not primary weights — added on top of weighted sum):
  d9_modifier        (D9 navamsha dignity):     +0.05 max
  yoga_bonus         (other yogas — Gaja/Budha/Panch Mahapurusha etc.):  +0.20 max  ← Rajayoga+VRY now explicit
  chandra_lagna      (Moon as Lagna bonus):     +0.03 max
  pd_lord_boost      (active PD lord, current): +0.03 max
  G21_VIMSOPAKA      (Vimsopaka bala ≥0.65):   weight 0.12
  G27_KP_CHAIN       (KP nakshatra chain):      weight 0.03
  G18_D10_FULL       (full Dashamsha score):    weight 0.01
  G26_KP_RULING      (KP ruling planets):       weight 0.00  (dropped)
  G25_KP_SSL         (KP Sub-Sub-Lord active):  weight 0.03
  G15_JAIMINI_CHARA  (Chara dasha alignment):   weight 0.01
  G1-G9 bonuses/penalties: additive deltas (combustion, retrograde, neecha_bhanga, etc.)

━━━ MISSING DATA PROTOCOL ━━━
If any predicted block field is null/missing:
  • Skip that specific sub-factor in attribution analysis.
  • Do not penalise the overall PAI for missing data.
  • Note the missing field in "data_quality_flags".

━━━ OUTPUT FORMAT ━━━
Return a single JSON object with EXACTLY the following keys:
{{
  "validator_version": "{VERSION}",
  "summary": {{
    "n_actual": int,
    "n_direct": int,
    "n_near": int,
    "n_miss": int,
    "n_predicted_miss": int,
    "PAI_strict": float,
    "PAI_relaxed": float,
    "precision": float,
    "recall": float,
    "f1_score": float,
    "timing_accuracy_months": float,
    "confidence_band": "EXCELLENT|GOOD|MODERATE|DEVELOPING|NEEDS_WORK",
    "one_line_verdict": str   // ≤ 25 words
  }},
  "event_matches": [
    {{
      "actual_event_index": int,
      "actual_date": "YYYY-MM",
      "actual_description": str,
      "matched_block_md": str,
      "matched_block_ad": str,
      "matched_block_start": "YYYY-MM",
      "matched_block_end": "YYYY-MM",
      "predicted_event_type": str,
      "predicted_career_score": float,
      "offset_months": float,
      "match_type": "DIRECT_HIT|NEAR_HIT|MISS",
      "active_signals": [str],   // list of factor IDs that were high in this block
      "miss_reason": str | null  // only for MISS
    }}
  ],
  "predicted_misses": [
    {{
      "block_md": str,
      "block_ad": str,
      "block_start": "YYYY-MM",
      "block_end": "YYYY-MM",
      "predicted_event_type": str,
      "predicted_career_score": float,
      "non_manifestation_hypothesis": "SUPPRESSED|DELAYED|INTERNAL|DATA_GAP",
      "suppression_factors": [str]  // which signals caused suppression
    }}
  ],
  "engine_gaps": [
    {{
      "actual_event_index": int,
      "actual_date": "YYYY-MM",
      "actual_description": str,
      "active_dasha_md": str,
      "active_dasha_ad": str,
      "active_dasha_pd": str,
      "engine_score_for_period": float | null,
      "root_cause": str,
      "signals_present_but_unscored": [str],
      "recommended_fix": str  // one sentence
    }}
  ],
  "factor_attribution": [
    {{
      "factor_id": str,
      "importance_score": float,   // 0.0-1.0
      "hit_count": int,            // how many DIRECT_HITs had this factor active
      "note": str                  // one sentence explaining its predictive pattern
    }}
  ],
  "engine_improvements": [
    {{
      "priority": int,        // 1=highest
      "factor_group": str,
      "current_weight": float | null,
      "observed_pattern": str,
      "recommended_action": str
    }}
  ],
  "data_quality_flags": [str]   // list of missing/incomplete data fields noticed
}}

Do not add any text outside the JSON object. Every string field must be non-null.
If a list is empty, return an empty array []. Never omit required keys.\
""".format(
    HIT_WINDOW=_HIT_WINDOW_MONTHS,
    NEAR_HIT_WINDOW=_NEAR_HIT_WINDOW_MONTHS,
    VERSION=VALIDATOR_VERSION,
)

# =============================================================================
# STEP 2 — NARRATOR SYSTEM PROMPT
# =============================================================================

_NARRATOR_SYSTEM_PROMPT = """\
You are a senior Jyotish career counselor writing an executive validation report. \
You have been given a completed structural validation analysis (Step 1 output) for a \
person's career journey. Your job is to synthesise these findings into a clear, \
actionable, human-readable report.

━━━ REPORT STRUCTURE ━━━
Write four sections:

SECTION 1 — OVERALL ASSESSMENT (2-3 paragraphs)
  • State the PAI (strict and relaxed), confidence band, and F1 score in plain language.
  • Characterise the engine's predictive quality for this specific chart.
  • Identify the single most striking pattern (e.g., "The engine excelled at timing
    promotions but consistently misclassified lateral moves").

SECTION 2 — PERIOD-BY-PERIOD ANALYSIS (one paragraph per career event)
  • For each actual event: what the engine predicted vs. what happened, and why they
    aligned or diverged.
  • For DIRECT_HITs: name the 2-3 most decisive astrological signals.
  • For NEAR_HITs: explain the timing or classification discrepancy.
  • For MISSES: explain the root cause without jargon overload (assume reader knows
    basic Vedic astrology but not the engine internals).

SECTION 3 — FACTOR RANKING INSIGHTS (1-2 paragraphs)
  • State the top 3 predictive factors and bottom 3.
  • Explain in plain terms why the top factors are so effective for this chart.
  • Name any surprise findings (a factor you expected to score high that scored low,
    or vice versa).

SECTION 4 — ENGINE IMPROVEMENT PLAN (one paragraph + numbered list)
  • Intro paragraph: overall calibration direction needed.
  • Numbered list: each engine_improvement recommendation from Step 1, stated as a
    clear action item with the specific weight or rule change required.

━━━ TONE AND STYLE ━━━
  • Write for a Jyotish practitioner who built the engine — technical but accessible.
  • Use astrological terminology where precise (MD, AD, KP sub-lord, Vimsopaka, etc.).
  • Avoid generic statements. Every claim must cite a specific event, period, or signal.
  • Maximum 600 words total. Do not pad with summaries or re-explanations.

━━━ OUTPUT FORMAT ━━━
Return a single JSON object:
{{
  "report_sections": {{
    "overall_assessment": str,
    "period_analysis": str,
    "factor_insights": str,
    "improvement_plan": str
  }},
  "executive_summary": str   // ≤ 40 words, suitable for a dashboard header
}}

Do not add any text outside the JSON object.\
"""

# =============================================================================
# JSON SCHEMAS
# =============================================================================

_VALIDATOR_RESPONSE_SCHEMA = {
    "name": "career_validator",
    "schema": {
        "type": "object",
        "properties": {
            "validator_version": {"type": "string"},
            "summary": {
                "type": "object",
                "properties": {
                    "n_actual":                {"type": "integer"},
                    "n_direct":                {"type": "integer"},
                    "n_near":                  {"type": "integer"},
                    "n_miss":                  {"type": "integer"},
                    "n_predicted_miss":        {"type": "integer"},
                    "PAI_strict":              {"type": "number"},
                    "PAI_relaxed":             {"type": "number"},
                    "precision":               {"type": "number"},
                    "recall":                  {"type": "number"},
                    "f1_score":                {"type": "number"},
                    "timing_accuracy_months":  {"type": "number"},
                    "confidence_band":         {"type": "string"},
                    "one_line_verdict":        {"type": "string"},
                },
                "required": [
                    "n_actual", "n_direct", "n_near", "n_miss", "n_predicted_miss",
                    "PAI_strict", "PAI_relaxed", "precision", "recall", "f1_score",
                    "timing_accuracy_months", "confidence_band", "one_line_verdict",
                ],
                "additionalProperties": False,
            },
            "event_matches": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "actual_event_index":      {"type": "integer"},
                        "actual_date":             {"type": "string"},
                        "actual_description":      {"type": "string"},
                        "matched_block_md":        {"type": "string"},
                        "matched_block_ad":        {"type": "string"},
                        "matched_block_start":     {"type": "string"},
                        "matched_block_end":       {"type": "string"},
                        "predicted_event_type":    {"type": "string"},
                        "predicted_career_score":  {"type": "number"},
                        "offset_months":           {"type": "number"},
                        "match_type":              {"type": "string"},
                        "active_signals":          {"type": "array", "items": {"type": "string"}},
                        "miss_reason":             {"type": ["string", "null"]},
                    },
                    "required": [
                        "actual_event_index", "actual_date", "actual_description",
                        "matched_block_md", "matched_block_ad",
                        "matched_block_start", "matched_block_end",
                        "predicted_event_type", "predicted_career_score",
                        "offset_months", "match_type", "active_signals", "miss_reason",
                    ],
                    "additionalProperties": False,
                },
            },
            "predicted_misses": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "block_md":                      {"type": "string"},
                        "block_ad":                      {"type": "string"},
                        "block_start":                   {"type": "string"},
                        "block_end":                     {"type": "string"},
                        "predicted_event_type":          {"type": "string"},
                        "predicted_career_score":        {"type": "number"},
                        "non_manifestation_hypothesis":  {"type": "string"},
                        "suppression_factors":           {"type": "array", "items": {"type": "string"}},
                    },
                    "required": [
                        "block_md", "block_ad", "block_start", "block_end",
                        "predicted_event_type", "predicted_career_score",
                        "non_manifestation_hypothesis", "suppression_factors",
                    ],
                    "additionalProperties": False,
                },
            },
            "engine_gaps": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "actual_event_index":            {"type": "integer"},
                        "actual_date":                   {"type": "string"},
                        "actual_description":            {"type": "string"},
                        "active_dasha_md":               {"type": "string"},
                        "active_dasha_ad":               {"type": "string"},
                        "active_dasha_pd":               {"type": "string"},
                        "engine_score_for_period":       {"type": ["number", "null"]},
                        "root_cause":                    {"type": "string"},
                        "signals_present_but_unscored":  {"type": "array", "items": {"type": "string"}},
                        "recommended_fix":               {"type": "string"},
                    },
                    "required": [
                        "actual_event_index", "actual_date", "actual_description",
                        "active_dasha_md", "active_dasha_ad", "active_dasha_pd", "engine_score_for_period",
                        "root_cause", "signals_present_but_unscored", "recommended_fix",
                    ],
                    "additionalProperties": False,
                },
            },
            "factor_attribution": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "factor_id":        {"type": "string"},
                        "importance_score": {"type": "number"},
                        "hit_count":        {"type": "integer"},
                        "note":             {"type": "string"},
                    },
                    "required": ["factor_id", "importance_score", "hit_count", "note"],
                    "additionalProperties": False,
                },
            },
            "engine_improvements": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "priority":             {"type": "integer"},
                        "factor_group":         {"type": "string"},
                        "current_weight":       {"type": ["number", "null"]},
                        "observed_pattern":     {"type": "string"},
                        "recommended_action":   {"type": "string"},
                    },
                    "required": [
                        "priority", "factor_group", "current_weight",
                        "observed_pattern", "recommended_action",
                    ],
                    "additionalProperties": False,
                },
            },
            "data_quality_flags": {"type": "array", "items": {"type": "string"}},
        },
        "required": [
            "validator_version", "summary", "event_matches", "predicted_misses",
            "engine_gaps", "factor_attribution", "engine_improvements",
            "data_quality_flags",
        ],
        "additionalProperties": False,
    },
    "strict": True,
}

_NARRATOR_RESPONSE_SCHEMA = {
    "name": "career_narrator",
    "schema": {
        "type": "object",
        "properties": {
            "report_sections": {
                "type": "object",
                "properties": {
                    "overall_assessment": {"type": "string"},
                    "period_analysis":    {"type": "string"},
                    "factor_insights":    {"type": "string"},
                    "improvement_plan":   {"type": "string"},
                },
                "required": [
                    "overall_assessment", "period_analysis",
                    "factor_insights", "improvement_plan",
                ],
                "additionalProperties": False,
            },
            "executive_summary": {"type": "string"},
        },
        "required": ["report_sections", "executive_summary"],
        "additionalProperties": False,
    },
    "strict": True,
}

# =============================================================================
# CHART SUMMARY BUILDER
# =============================================================================

def build_chart_summary_for_validation(payload: Any) -> str:
    """
    Build a concise chart summary string for the validation prompt.
    Mirrors _build_chart_summary_for_llm() in jyotish/llm.py.

    Args:
        payload: NatalPayloadV2 or any object / dict with standard chart fields.

    Returns:
        Multi-line string with all chart signals needed for validation.
    """
    def _g(key: str, default: Any = "not available") -> Any:
        if isinstance(payload, dict):
            return payload.get(key, default)
        return getattr(payload, key, default) or default

    def _fmt_planet_house(ph: Dict) -> str:
        if not ph:
            return "not available"
        return ", ".join(f"{p}→H{h}" for p, h in sorted(ph.items()) if h)

    def _fmt_dignities(digs: Any) -> str:
        if not digs:
            return "not available"
        if isinstance(digs, dict):
            parts = [f"{p}:{d}" for p, d in digs.items() if d]
            return ", ".join(parts) or "not available"
        return str(digs)

    # Core identifiers
    name          = _g("name", "Unknown")
    dob           = _g("dob", "not available")
    lagna         = _g("lagna_sign", "not available")
    ak            = _g("atmakaraka", "not available")
    amk           = _g("amatyakaraka", "not available")
    # Chara Karakas — now formal fields on NatalPayloadV2; fall back to
    # kn_rao_jaimini["chara_karakas"] for any legacy payload that lacks them.
    _kn_rao       = _g("kn_rao_jaimini", {}) or {}
    _cc           = (_kn_rao.get("chara_karakas") or {}) if isinstance(_kn_rao, dict) else {}
    mk            = _g("matrikaraka", "") or _cc.get("MK", "not available")
    bk            = _g("bhatrikaraka", "") or _cc.get("BK", "not available")
    pk            = _g("putrakaraka", "") or _cc.get("PK", "not available")
    gnk           = _g("gnatikaraka", "") or _cc.get("GnK", "not available")
    dk            = _g("darakaraka", "") or _cc.get("DK", "not available")

    planet_house  = _g("planet_house", {})
    house_lords   = _g("house_lords", {})
    # NatalPayloadV2 uses planet_signs (plural); "planet_sign" is a legacy alias
    planet_sign   = _g("planet_signs", {}) or _g("planet_sign", {}) or {}
    # NatalPayloadV2 uses planet_dignities (D1) and d9_planet_dignities (D9)
    dignities     = _g("planet_dignities", _g("dignities", {}))
    retrogrades   = _g("retrograde_planets", [])

    # KP data
    # CAVEAT (2026-08-21, remediation plan item 2.4, lower-priority): this KP
    # cusp data is fed to the LLM prompt as-is, with no birth-time-precision
    # or cusp-verification caveat attached — unlike the Tier 6 KP scoring
    # path in Job_Career/astro_enhancer.py, which now degrades its
    # contribution under birth-time uncertainty and unverified cusp chains
    # (see enhancer_score_delta()). Display/prompt text only (not scoring
    # math), so left as a flagged caveat here rather than changed, per the
    # remediation plan's explicit "more liberty here" scoping for this item.
    kp_cusps      = _g("kp_cusps", {}) or {}
    h10_kp        = kp_cusps.get("H10", {}) or {}
    h11_kp        = kp_cusps.get("H11", {}) or {}
    h6_kp         = kp_cusps.get("H6",  {}) or {}
    h2_kp         = kp_cusps.get("H2",  {}) or {}

    # Dasha — prefer the full sequence (with dates + ADs); fall back to stripped version
    _dasha_full   = _g("vimshottari_dasha_full", []) or []
    dasha_seq     = _dasha_full if _dasha_full else (_g("dasha_sequence", []) or [])
    current_age   = _g("current_age", "not available")

    # D9 — NatalPayloadV2 field is d9_planet_dignities (not d9_dignities)
    d9_dignities   = _g("d9_planet_dignities", _g("d9_dignities", {}))
    # D10 — now formal fields on NatalPayloadV2 (Steps 1-2 fix)
    d10_lagna      = _g("d10_lagna_sign", "not available")
    d10_h_lords    = _g("d10_house_lords", {}) or {}
    d10_h_occ      = _g("d10_house_occupancy", {}) or {}
    d10_planet_sign = _g("d10_planet_sign", {}) or {}      # {planet: sign} if available

    # Yogas — NatalPayloadV2 uses detected_yogas (List[str]); "yogas" dict is a legacy format.
    # detected_yogas is the authoritative source; fall back through yogas_present → yogas.
    yogas_raw     = (_g("detected_yogas", None) or _g("yogas_present", None)
                     or _g("yogas", None) or [])
    yoga_names    = list(yogas_raw.keys()) if isinstance(yogas_raw, dict) else list(yogas_raw or [])

    # Nakshatra — Step 3 fix: moon_nakshatra is now a formal string field on NatalPayloadV2.
    # nakshatra_data["Moon"] may still be a string or dict; handle both defensively.
    _nak_data     = _g("nakshatra_data", {}) or {}
    moon_nak_raw  = _nak_data.get("Moon") or ""
    if isinstance(moon_nak_raw, dict):
        moon_nak  = moon_nak_raw.get("nakshatra") or moon_nak_raw.get("name") or ""
        moon_pada = (moon_nak_raw.get("pada")
                     or _g("moon_nakshatra_pada", 0)   # formal field (int, 1-4)
                     or "not available")
    else:
        moon_nak  = (_g("moon_nakshatra", "") or str(moon_nak_raw)) or "not available"
        moon_pada = _g("moon_nakshatra_pada", "not available")  # formal field set by engine_io.py

    lagna_nak_raw = _nak_data.get("Lagna") or ""
    lagna_nak     = (lagna_nak_raw.get("nakshatra") if isinstance(lagna_nak_raw, dict)
                     else (str(lagna_nak_raw) if lagna_nak_raw else ""))
    if not lagna_nak:
        lagna_nak = _g("lagna_nakshatra", "not available")   # formal field set by engine_io.py

    # Planet nakshatras — now a formal field on NatalPayloadV2 (planet_nakshatras)
    planet_nakshatras = _g("planet_nakshatras", {}) or {}

    # Karakamsha — NatalPayloadV2 has karakamsha (the D9 sign of AK)
    karakamsha    = _g("karakamsha", _g("karakamsha_sign", "not available"))
    # Arudha / A10 — Step 4-5 fix: field is "arudha_lagna" (not "arudha_lagna_sign"),
    # and "a10_sign" is now stored by engine.py after compute_arudha_pada(10,...).
    cc_inner      = _g("career_context", {}) or {}
    arudha_lagna  = (_g("arudha_lagna", "")              # formal field set by engine.py
                     or cc_inner.get("arudha_lagna_sign")
                     or cc_inner.get("arudha_lagna")
                     or "not available")
    a10_sign      = (_g("a10_sign", "")                  # formal field set by engine.py
                     or cc_inner.get("a10_sign")
                     or cc_inner.get("karma_pada")
                     or "not available")

    # Career context
    cc            = cc_inner
    sector        = cc.get("industry_sector", _g("industry_sector", "not available"))
    designation   = cc.get("designation") or _g("designation", "not available")
    exp_years     = (cc.get("years_experience")          # key set by parse_career_context
                     or cc.get("experience_years")       # legacy alias
                     or _g("experience_years", "not available"))

    lines = [
        f"━━━ CHART SUMMARY: {name} ━━━",
        f"DOB: {dob}  |  Lagna: {lagna}  |  Current Age: {current_age}",
        f"Sector: {sector}  |  Designation: {designation}  |  Experience: {exp_years} yrs",
        "",
        "── KARAKAS ──────────────────────────────────────────",
        f"AK  (Atmakaraka):  {ak}  |  AmK (Amatyakaraka): {amk}",
        f"MK  (Matrikaraka): {mk}  |  BK  (Bhatrikaraka): {bk}",
        f"PK  (Putrakaraka): {pk}  |  GnK (Gnatikaraka):  {gnk}",
        f"DK  (Darakaraka):  {dk}",
        "",
        "── PLANET HOUSES (D1 Rasi) ─────────────────────────",
        _fmt_planet_house(planet_house if isinstance(planet_house, dict) else {}),
        "",
        "── HOUSE LORDS ─────────────────────────────────────",
        ", ".join(f"H{k}:{v}" for k, v in sorted((house_lords or {}).items())) or "not available",
        "",
        "── PLANET SIGNS ────────────────────────────────────",
        ", ".join(f"{p}:{s}" for p, s in sorted((planet_sign or {}).items())) or "not available",
        "",
        "── DIGNITIES (D1) ──────────────────────────────────",
        _fmt_dignities(dignities),
        "",
        f"── RETROGRADE PLANETS: {', '.join(retrogrades) if retrogrades else 'None'} ──",
        "",
        "── KP CUSP DATA ─────────────────────────────────────",
        f"H10: star={h10_kp.get('star_lord','?')} sub={h10_kp.get('sub_lord','?')} ssl={h10_kp.get('sub_sub_lord','?')}",
        f"H11: star={h11_kp.get('star_lord','?')} sub={h11_kp.get('sub_lord','?')} ssl={h11_kp.get('sub_sub_lord','?')}",
        f"H6:  star={h6_kp.get('star_lord','?')}  sub={h6_kp.get('sub_lord','?')}",
        f"H2:  star={h2_kp.get('star_lord','?')}  sub={h2_kp.get('sub_lord','?')}",
        "",
        "── D9 NAVAMSHA DIGNITIES ────────────────────────────",
        _fmt_dignities(d9_dignities),
        "",
        "── D10 DASHAMSHA (Career Chart) ─────────────────────",
        f"D10 Lagna: {d10_lagna}",
        f"D10 House Lords: {', '.join(f'H{k}:{v}' for k,v in sorted((d10_h_lords or {}).items())) or 'not available'}",
    ]
    # D10 house occupancy — which planets sit in which D10 house
    if d10_h_occ:
        _occ_parts = []
        for _h in sorted(d10_h_occ.keys(), key=lambda x: int(x) if str(x).isdigit() else 99):
            _planets = d10_h_occ[_h]
            if _planets:
                _occ_parts.append(f"H{_h}:[{','.join(_planets)}]")
        if _occ_parts:
            lines.append(f"D10 Planet Occupancy: {', '.join(_occ_parts)}")
    # D10 planet signs
    if d10_planet_sign:
        lines.append(
            f"D10 Planet Signs: "
            + ", ".join(f"{p}:{s}" for p, s in sorted(d10_planet_sign.items()))
        )
    lines += [
        "",
        "── NAKSHATRA / SPECIAL LAGNAS ───────────────────────",
        f"Moon Nakshatra: {moon_nak} Pada {moon_pada}  |  Lagna Nakshatra: {lagna_nak}",
        f"Karakamsha (D9 AK sign): {karakamsha}",
        f"Arudha Lagna (A1): {arudha_lagna}  |  Karma Pada (A10): {a10_sign}",
        (("Planet Nakshatras: "
          + ", ".join(f"{p}:{n}" for p, n in sorted(planet_nakshatras.items()) if n))
         if planet_nakshatras else "Planet Nakshatras: not available"),
        "",
        "── D10 DEVATA DIAGNOSTICS ───────────────────────────",
        "Four career-problem archetypes derived from Dasamsa (D10).",
        "Each archetype identifies the key planet (lord) and its devata.",
        "When this devata is unworshipped/weak, the archetype manifests strongly.",
    ] + _build_d10_devata_lines(_g("d10_devata_diagnostics", {})) + [
        "",
        "── ACTIVE YOGAS ─────────────────────────────────────",
        (", ".join(yoga_names[:20]) if yoga_names else "not available"),
        "",
        "── COMPLETE VIMSHOTTARI DASHA (MD → AD → PD with calendar dates) ───────────",
    ]

    if dasha_seq and isinstance(dasha_seq, list):
        for ds in dasha_seq:
            if not isinstance(ds, dict):
                continue
            md_planet = (ds.get("planet") or ds.get("md_planet")
                         or ds.get("lord") or "?")
            md_start  = (ds.get("start") or ds.get("start_date") or
                         (f"age {ds.get('start_age','?')}" if ds.get("start_age") else "?"))
            md_end    = (ds.get("end") or ds.get("end_date") or
                         (f"age {ds.get('end_age','?')}" if ds.get("end_age") else "?"))
            lines.append(f"  MD {md_planet}: {md_start} → {md_end}")

            ads = ds.get("antardashas") or ds.get("sub_periods") or []
            for ad in ads:
                if not isinstance(ad, dict):
                    continue
                ad_planet = ad.get("planet") or ad.get("ad_planet") or ad.get("lord") or "?"
                ad_start  = (ad.get("start") or ad.get("start_date") or
                             (f"age {ad.get('start_age','?')}" if ad.get("start_age") else "?"))
                ad_end    = (ad.get("end") or ad.get("end_date") or
                             (f"age {ad.get('end_age','?')}" if ad.get("end_age") else "?"))
                lines.append(f"    AD {ad_planet}: {ad_start} → {ad_end}")

                # Pratyantardashas (3rd level) — key for precise event timing
                pds = ad.get("pratyantardashas") or []
                for pd in pds:
                    if not isinstance(pd, dict):
                        continue
                    pd_planet = pd.get("planet") or pd.get("pd_lord") or "?"
                    pd_start  = pd.get("start_date") or pd.get("start") or "?"
                    pd_end    = pd.get("end_date") or pd.get("end") or "?"
                    lines.append(f"      PD {pd_planet}: {pd_start} → {pd_end}")
    else:
        lines.append("  not available")

    return "\n".join(lines)


# =============================================================================
# USER MESSAGE BUILDER — STEP 1 (VALIDATOR)
# =============================================================================

def build_validator_user_message(
    chart_summary: str,
    predicted_blocks: List[Dict],
    actual_history: List[Dict],
    score_threshold: float = 0.55,
) -> str:
    """
    Build the user message for the Step 1 validator call.

    Args:
        chart_summary:     Output of build_chart_summary_for_validation().
        predicted_blocks:  Career timeline blocks from build_career_timeline().
                           Each block should include: md_lord, ad_lord, start_date,
                           end_date, career_score, event_type, yoga_flags,
                           kp_cusp_score, enhancer_total_delta, and all enhancer
                           sub-fields (combustion_modifier, retrograde_modifier,
                           dig_bala_factor, vimsopaka_score, etc.)
        actual_history:    List of dicts with keys:
                             date (YYYY-MM), description (str),
                             intensity (0-10, optional), company (str, optional)
        score_threshold:   Career score above which a predicted block is considered
                           a "prediction" (blocks below this are background noise).

    Returns:
        str: The complete user message for Step 1.
    """
    # Filter to significant predicted blocks
    sig_blocks = [b for b in predicted_blocks if b.get("career_score", 0) >= score_threshold]
    # Include all blocks for context (engine sees full timeline)
    all_blocks = predicted_blocks

    # Compact block representation
    # NOTE: build_career_timeline() nests all _score_period sub-fields inside
    # block["sub_scores"]. The only top-level score field is "career_score".
    # Enhancer fields (vimsopaka_score, yogini_name, is_sandhi, event_hints, etc.)
    # are ALL inside sub_scores — not at the block's top level.
    def _fmt_block(b: Dict, idx: int) -> str:
        ss = b.get("sub_scores", {}) or {}   # ← all enhancer + sub-score fields live here
        signals = []
        # active_yogas is in sub_scores (set by _detect_natal_yogas via _score_period)
        yogas_list = ss.get("active_yogas", [])
        if yogas_list:
            signals.append(f"yogas={','.join(yogas_list[:3])}")
        # kp_cusp_score is in sub_scores
        kp = ss.get("kp_cusp_score", ss.get("kp_cusp_alignment", b.get("kp_cusp_alignment", 0)))
        if kp:
            signals.append(f"kp={kp:.2f}")
        # All enhancer fields are in sub_scores
        enh = ss.get("enhancer_total_delta", 0)
        if enh:
            signals.append(f"enh_delta={enh:+.3f}")
        for fk in ["vimsopaka_score", "chara_dasha_score", "yogini_score",
                   "d10_full_score", "kp_ssl_score"]:
            v = ss.get(fk, 0)
            if v:
                signals.append(f"{fk.split('_')[0]}={v:.2f}")
        # Yogini dasha name
        yog_name = ss.get("yogini_name", "")
        if yog_name:
            signals.append(f"yogini={yog_name}")
        for flag_key in ["nakshatra_triggers", "mars_aspect_flags", "transit_aspect_flags"]:
            fl = ss.get(flag_key, [])
            if fl:
                signals.append(f"{flag_key[:6]}={len(fl)}")

        line = (
            f"[{idx:02d}] {b.get('md_lord','?')}/{b.get('ad_lord','?')}  "
            f"{b.get('start_date','?')}→{b.get('end_date','?')}  "
            f"score={b.get('career_score',0):.3f}  "
            f"type={b.get('event_type','?')}"
        )
        if signals:
            line += f"  [{'; '.join(signals)}]"
        # Sandhi / risk flags — all in sub_scores
        extras = []
        if ss.get("is_sandhi"):
            extras.append("SANDHI")
        if ss.get("kala_sarpa_modifier", 0) < -0.01:
            extras.append("KALA_SARPA")
        if ss.get("papa_kartari_penalty", 0) < -0.01:
            extras.append("PAPA_KARTARI")
        event_hints = ss.get("event_hints", [])
        if event_hints:
            extras += event_hints[:2]
        if extras:
            line += f"  !{','.join(extras)}"
        return line

    blocks_text = "\n".join(_fmt_block(b, i) for i, b in enumerate(all_blocks, 1))

    # Actual history
    # Supports two formats:
    #   Validator format:     {date, description, company, intensity}
    #   career_events format: {date, event_type, role, company, notes}
    #
    # Gap-audit fix (2026-08): description/role/company/notes/event_type are
    # free-text fields sourced directly from the end user (this is the one
    # place in the LLM-integration layer where genuine user-supplied text
    # reaches a prompt, as opposed to the server-controlled structured data
    # used everywhere else in this file). Previously interpolated verbatim
    # with no escaping or length bound, which meant a user could: (a) embed
    # newlines + fake `[Axx]`/`━━━ ... ━━━` section markers to try to forge
    # additional history entries or spoof a new prompt section boundary,
    # confusing the structured [Axx]-index matching the validator LLM relies
    # on, or (b) submit an unbounded-length string to inflate token usage /
    # push other content out of context. _sanitize_user_text() below strips
    # control/newline characters (collapsing them to a single space, so a
    # multi-line "event description" still reads as one line and cannot
    # inject a fake delimiter/section boundary) and caps length. This does
    # not change any scoring/validation logic -- only how untrusted text is
    # embedded into the prompt string.
    def _fmt_event(e: Dict, idx: int) -> str:
        desc = (e.get("description")
                or e.get("notes")
                or e.get("event_type", "?").replace("_", " ").title())
        desc = _sanitize_user_text(desc)
        role = _sanitize_user_text(e.get("role", ""))
        if role and role not in desc:
            desc = f"{role} — {desc}"
        parts = [f"[A{idx:02d}]", e.get("date", "?"), "|", desc]
        co = _sanitize_user_text(e.get("company", ""))
        if co:
            parts += ["@", co]
        intensity = e.get("intensity", "")
        if intensity != "":
            parts += [f"intensity={intensity}/10"]
        return " ".join(str(p) for p in parts)

    history_text = "\n".join(_fmt_event(e, i) for i, e in enumerate(actual_history, 1))

    # Factor reference (for attribution analysis)
    factor_ref = ", ".join(_FACTOR_IDS)

    # Determine validation horizon from actual history dates
    _actual_dates = sorted(
        [e.get("date", "") for e in actual_history if e.get("date")],
    )
    _hist_start = _actual_dates[0]  if _actual_dates else "earliest available"
    _hist_end   = _actual_dates[-1] if _actual_dates else "latest available"

    user_msg = (
        f"{chart_summary}\n\n"
        f"━━━ ENGINE-PREDICTED CAREER TIMELINE ({len(all_blocks)} blocks, "
        f"{len(sig_blocks)} significant [score≥{score_threshold}]) ━━━\n"
        f"Format: [idx] MD/AD  start→end  score  type  [active signals]  !flags\n"
        f"{blocks_text}\n\n"
        f"━━━ ACTUAL CAREER HISTORY ({len(actual_history)} events, "
        f"spanning {_hist_start} → {_hist_end}) ━━━\n"
        f"Format: [Axx] YYYY-MM | description @ company  intensity=x/10\n"
        f"{history_text}\n\n"
        f"━━━ FACTOR ID REFERENCE (for factor_attribution output) ━━━\n"
        f"{factor_ref}\n\n"
        f"━━━ VALIDATION SCOPE (you decide) ━━━\n"
        f"You have been given the FULL dasha sequence from DOB and ALL predicted blocks "
        f"covering the person's career history (from {_hist_start}) through the forecast window. "
        f"Do NOT restrict your validation to any fixed number of years. "
        f"Validate every actual career event in the history above, regardless of how far back it "
        f"falls. The full Mahadasha + Antardasha sequence is in the chart summary — use it to "
        f"identify which MD/AD was active for each actual event, even those predating the "
        f"predicted-blocks window. For periods outside the predicted-blocks list, set "
        f"engine_score_for_period=null and root_cause='INSUFFICIENT_DATA' or the most accurate "
        f"alternative root cause you can derive from the dasha sequence alone.\n\n"
        f"━━━ TASK ━━━\n"
        f"Perform the 7-step validation as specified in the system prompt. "
        f"Return the complete JSON object. "
        f"Match each actual event [A01..A{len(actual_history):02d}] to the best predicted block. "
        f"Only blocks with score≥{score_threshold} count as active predictions for PAI/precision. "
        f"All 7 steps are mandatory."
    )
    return user_msg


# =============================================================================
# USER MESSAGE BUILDER — STEP 2 (NARRATOR)
# =============================================================================

def build_narrator_user_message(
    chart_summary: str,
    validation_result: Dict,
) -> str:
    """
    Build the user message for the Step 2 narrator call.

    Args:
        chart_summary:      Same summary string used in Step 1.
        validation_result:  Parsed Step 1 JSON output (dict).

    Returns:
        str: The complete user message for Step 2.
    """
    return (
        f"{chart_summary}\n\n"
        f"━━━ STEP 1 VALIDATION RESULT ━━━\n"
        f"{json.dumps(validation_result, indent=2, ensure_ascii=False)}\n\n"
        f"━━━ TASK ━━━\n"
        f"Write the four-section validation report as specified. "
        f"Maximum 600 words. Return the JSON object only."
    )


# =============================================================================
# PAYLOAD → ACTUAL HISTORY EXTRACTOR  (Gap 6)
# =============================================================================

def extract_actual_history_from_payload(payload: Any) -> List[Dict]:
    """
    Extract the user's actual career event history from a NatalPayloadV2.

    The engine stores actual past events in two places:
      1. career_context["career_events"]  — list of {date, event_type, role, company, notes}
      2. career_context legacy fields     — join_date, last_promotion_date, last_hike_date

    Returns a list of dicts compatible with build_validator_user_message(), each with:
      {date, description, company, intensity}
    """
    def _g(key: str, default: Any = None) -> Any:
        if isinstance(payload, dict):
            return payload.get(key, default)
        return getattr(payload, key, default)

    cc = _g("career_context", {}) or {}
    events: List[Dict] = []

    # 1. Full career_events list
    for evt in (cc.get("career_events") or []):
        if not isinstance(evt, dict):
            continue
        d = evt.get("date", "")
        if not d:
            continue
        desc = (evt.get("description")
                or evt.get("notes")
                or evt.get("event_type", "Career event").replace("_", " ").title())
        role = evt.get("role", "")
        if role and role not in desc:
            desc = f"{role} — {desc}"
        events.append({
            "date":        d[:7],          # YYYY-MM
            "description": desc,
            "company":     evt.get("company", ""),
            "intensity":   evt.get("intensity", ""),
        })

    # 2. Legacy date fields
    legacy = [
        ("join_date",           "Joined current company"),
        ("last_promotion_date", "Last promotion"),
        ("last_hike_date",      "Last salary hike"),
    ]
    for field, label in legacy:
        d = cc.get(field, "")
        if d and not any(e["date"] == d[:7] for e in events):
            events.append({"date": d[:7], "description": label, "company": "", "intensity": ""})

    # Sort chronologically
    events.sort(key=lambda e: e.get("date", ""))
    return events


# =============================================================================
# LLM CALL  (mirrors call_llm_for_fields in jyotish/llm.py)
# =============================================================================

def call_validation_llm(
    payload: Any,
    predicted_blocks: List[Dict],
    actual_history: List[Dict],
    *,
    score_threshold: float = 0.55,
    model: str = "gpt-5.4-mini",
    temperature: float = 0.1,
    timeout: int = 120,
) -> Dict:
    """
    Run the two-step career validation pipeline against an LLM.

    Args:
        payload:           NatalPayloadV2 or dict.
        predicted_blocks:  Output of build_career_timeline()['blocks'].
        actual_history:    List of dicts [{date, description, company, intensity}, ...].
        score_threshold:   Minimum career_score to treat a block as a prediction.
        model:             OpenAI model string.
        temperature:       LLM temperature (low = deterministic).
        timeout:           Per-call timeout in seconds.

    Returns:
        dict with keys:
          "validation" : dict  (Step 1 structured output)
          "narrative"  : dict  (Step 2 report sections)
          "raw_step1"  : str
          "raw_step2"  : str
    """
    import openai

    api_key = os.environ.get("OPENAI_API_KEY", "")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY not set. Cannot call LLM for validation.")

    client = openai.OpenAI(api_key=api_key)

    chart_summary = build_chart_summary_for_validation(payload)
    user_msg_1    = build_validator_user_message(
        chart_summary, predicted_blocks, actual_history,
        score_threshold=score_threshold,
    )

    logger.info("[Validation] Step 1 — Validator call (%s)", model)

    resp1 = client.chat.completions.create(
        model=model,
        temperature=temperature,
        timeout=timeout,
        response_format={
            "type": "json_schema",
            "json_schema": _VALIDATOR_RESPONSE_SCHEMA,
        },
        messages=[
            {"role": "system",  "content": _VALIDATOR_SYSTEM_PROMPT},
            {"role": "user",    "content": user_msg_1},
        ],
    )
    raw1 = resp1.choices[0].message.content or ""

    try:
        validation_result = json.loads(raw1)
    except json.JSONDecodeError as exc:
        logger.error("[Validation] Step 1 JSON parse error: %s\nRaw: %s", exc, raw1[:300])
        validation_result = {"error": str(exc), "raw": raw1}

    logger.info(
        "[Validation] Step 1 complete — PAI_relaxed=%.2f  band=%s",
        validation_result.get("summary", {}).get("PAI_relaxed", 0.0),
        validation_result.get("summary", {}).get("confidence_band", "N/A"),
    )

    user_msg_2 = build_narrator_user_message(chart_summary, validation_result)

    logger.info("[Validation] Step 2 — Narrator call (%s)", model)

    resp2 = client.chat.completions.create(
        model=model,
        temperature=temperature,
        timeout=timeout,
        response_format={
            "type": "json_schema",
            "json_schema": _NARRATOR_RESPONSE_SCHEMA,
        },
        messages=[
            {"role": "system",  "content": _NARRATOR_SYSTEM_PROMPT},
            {"role": "user",    "content": user_msg_2},
        ],
    )
    raw2 = resp2.choices[0].message.content or ""

    try:
        narrative_result = json.loads(raw2)
    except json.JSONDecodeError as exc:
        logger.error("[Validation] Step 2 JSON parse error: %s\nRaw: %s", exc, raw2[:300])
        narrative_result = {"error": str(exc), "raw": raw2}

    return {
        "validation": validation_result,
        "narrative":  narrative_result,
        "raw_step1":  raw1,
        "raw_step2":  raw2,
    }


# =============================================================================
# HTML REPORT GENERATOR
# =============================================================================

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Career Validation Report — {name}</title>
<style>
  :root {{
    --bg: #0d1117; --card: #161b22; --border: #30363d;
    --text: #c9d1d9; --accent: #58a6ff; --success: #3fb950;
    --warn: #d29922; --danger: #f85149; --near: #e3b341;
    --muted: #8b949e;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text); font-family: 'Segoe UI', sans-serif;
          font-size: 14px; line-height: 1.6; padding: 24px; }}
  h1 {{ color: var(--accent); font-size: 22px; margin-bottom: 4px; }}
  h2 {{ color: var(--accent); font-size: 16px; margin: 20px 0 10px; border-bottom: 1px solid var(--border); padding-bottom: 4px; }}
  h3 {{ color: var(--text); font-size: 14px; margin: 12px 0 6px; }}
  .exec-summary {{ background: var(--card); border: 1px solid var(--accent);
                   border-radius: 8px; padding: 14px 18px; margin-bottom: 20px; font-size: 15px; }}
  .metrics {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
              gap: 12px; margin-bottom: 20px; }}
  .metric {{ background: var(--card); border: 1px solid var(--border); border-radius: 6px;
             padding: 12px; text-align: center; }}
  .metric .label {{ font-size: 11px; color: var(--muted); text-transform: uppercase; }}
  .metric .value {{ font-size: 22px; font-weight: bold; margin-top: 4px; }}
  .band-EXCELLENT {{ color: var(--success); }}
  .band-GOOD      {{ color: #4ec9b0; }}
  .band-MODERATE  {{ color: var(--warn); }}
  .band-DEVELOPING {{ color: var(--near); }}
  .band-NEEDS_WORK {{ color: var(--danger); }}
  .events-table {{ width: 100%; border-collapse: collapse; margin-bottom: 20px; }}
  .events-table th {{ background: var(--card); color: var(--muted); font-size: 11px;
                      text-transform: uppercase; padding: 8px; text-align: left;
                      border-bottom: 1px solid var(--border); }}
  .events-table td {{ padding: 8px; border-bottom: 1px solid var(--border); vertical-align: top; }}
  .events-table tr:hover td {{ background: rgba(88,166,255,.05); }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px;
            font-size: 11px; font-weight: bold; }}
  .badge-DIRECT_HIT {{ background: rgba(63,185,80,.2); color: var(--success); }}
  .badge-NEAR_HIT   {{ background: rgba(210,153,34,.2); color: var(--near); }}
  .badge-MISS       {{ background: rgba(248,81,73,.2); color: var(--danger); }}
  .factors-grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
                   gap: 8px; margin-bottom: 20px; }}
  .factor-card {{ background: var(--card); border: 1px solid var(--border); border-radius: 6px;
                  padding: 10px 12px; }}
  .factor-name  {{ font-size: 12px; color: var(--accent); font-weight: bold; }}
  .factor-bar-bg {{ background: var(--border); border-radius: 3px; height: 6px; margin: 4px 0; }}
  .factor-bar    {{ background: var(--accent); border-radius: 3px; height: 6px; }}
  .factor-meta   {{ font-size: 11px; color: var(--muted); }}
  .improve-list  {{ list-style: none; }}
  .improve-list li {{ background: var(--card); border-left: 3px solid var(--accent);
                      padding: 10px 14px; margin-bottom: 8px; border-radius: 0 6px 6px 0; }}
  .improve-list .pri {{ font-size: 11px; color: var(--muted); }}
  .improve-list .factor {{ color: var(--accent); font-weight: bold; margin: 2px 0; }}
  .section-prose {{ background: var(--card); border: 1px solid var(--border); border-radius: 6px;
                    padding: 14px 18px; margin-bottom: 14px; white-space: pre-line; }}
  .data-flags-grid {{ display: flex; flex-direction: column; gap: 6px; margin-bottom: 14px; }}
  .dq-flag       {{ display: flex; align-items: flex-start; gap: 10px; background: rgba(248,81,73,.06);
                    border: 1px solid rgba(248,81,73,.25); border-radius: 6px; padding: 8px 12px; }}
  .dq-flag.flag-critical {{ border-color: rgba(248,81,73,.55); background: rgba(248,81,73,.10); }}
  .dq-flag.flag-high     {{ border-color: rgba(227,179,65,.45); background: rgba(227,179,65,.07); }}
  .dq-flag.flag-medium   {{ border-color: rgba(88,166,255,.30); background: rgba(88,166,255,.06); }}
  .dq-icon       {{ font-size: 14px; margin-top: 1px; flex-shrink: 0; }}
  .dq-text       {{ font-size: 12.5px; color: var(--text); font-weight: 500; }}
  .dq-impact     {{ font-size: 11px; color: var(--muted); margin-top: 2px; }}
  .plan-item     {{ background: var(--card); border-radius: 6px; border-left: 3px solid var(--accent);
                    padding: 10px 14px; margin-bottom: 8px; }}
  .plan-item.plan-critical {{ border-left-color: #f85149; }}
  .plan-item.plan-high     {{ border-left-color: #e3b341; }}
  .plan-item.plan-medium   {{ border-left-color: var(--accent); }}
  .plan-step     {{ font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; color: var(--muted); }}
  .plan-action   {{ font-size: 13px; font-weight: 600; color: var(--text); margin: 3px 0; }}
  .plan-field    {{ font-size: 11px; color: var(--accent); font-family: monospace;
                    background: rgba(88,166,255,.10); border-radius: 3px; padding: 1px 5px; }}
  .plan-effect   {{ font-size: 11.5px; color: var(--muted); margin-top: 4px; }}
  .tag {{ display: inline-block; padding: 1px 6px; border-radius: 3px;
          font-size: 10px; background: rgba(88,166,255,.15); color: var(--accent);
          margin: 1px; }}
  footer {{ color: var(--muted); font-size: 11px; margin-top: 30px;
            border-top: 1px solid var(--border); padding-top: 10px; }}
</style>
</head>
<body>
<h1>Career Validation Report</h1>
<p style="color:var(--muted);margin-bottom:16px;">{name} &nbsp;·&nbsp; Generated {today} &nbsp;·&nbsp; {version}</p>

{retro_gap_html}

<div class="exec-summary">{exec_summary}</div>

<h2>Accuracy Metrics</h2>
<div class="metrics">
  <div class="metric"><div class="label">PAI Strict</div><div class="value" style="color:var(--accent)">{PAI_strict:.0%}</div></div>
  <div class="metric"><div class="label">PAI Relaxed</div><div class="value" style="color:var(--accent)">{PAI_relaxed:.0%}</div></div>
  <div class="metric"><div class="label">Precision</div><div class="value">{precision:.0%}</div></div>
  <div class="metric"><div class="label">Recall</div><div class="value">{recall:.0%}</div></div>
  <div class="metric"><div class="label">F1 Score</div><div class="value">{f1:.0%}</div></div>
  <div class="metric"><div class="label">Timing Accuracy</div><div class="value">{timing:.1f}<span style="font-size:12px"> mo</span></div></div>
  <div class="metric"><div class="label">Direct Hits</div><div class="value" style="color:var(--success)">{n_direct}/{n_actual}</div></div>
  <div class="metric"><div class="label">Near Hits</div><div class="value" style="color:var(--near)">{n_near}</div></div>
  <div class="metric"><div class="label">Misses</div><div class="value" style="color:var(--danger)">{n_miss}</div></div>
  <div class="metric"><div class="label">Confidence Band</div><div class="value band-{band}" style="font-size:14px">{band}</div></div>
</div>

<h2>Event-by-Event Match Analysis</h2>
<table class="events-table">
  <thead><tr>
    <th>#</th><th>Actual Event</th><th>Match Type</th><th>Predicted Period</th>
    <th>Pred Type</th><th>Score</th><th>Offset</th><th>Key Signals</th>
  </tr></thead>
  <tbody>{event_rows}</tbody>
</table>

{predicted_misses_html}

{engine_gaps_html}

<h2>Factor Attribution Ranking</h2>
<div class="factors-grid">{factor_cards}</div>

<h2>Engine Improvement Plan</h2>
<ul class="improve-list">{improve_items}</ul>

<h2>Narrative Report</h2>
<h3>Overall Assessment</h3>
<div class="section-prose">{sec_overall}</div>
<h3>Period-by-Period Analysis</h3>
<div class="section-prose">{sec_period}</div>
<h3>Factor Ranking Insights</h3>
<div class="section-prose">{sec_factors}</div>
<h3>Improvement Plan</h3>
{computed_plan_html}

{data_flags_html}

<footer>{version} &nbsp;&middot;&nbsp; JyotishAI Career Validation Engine</footer>
</body>
</html>
"""


def generate_validation_html(
    llm_result: Dict,
    payload: Any,
    output_dir: str = ".",
) -> str:
    """Render the validation result as a self-contained HTML report."""
    import html as html_lib
    from datetime import date as _date, timedelta as _td

    def _g(key: str, default: Any = "") -> Any:
        if isinstance(payload, dict):
            return payload.get(key, default)
        return getattr(payload, key, default) or default

    name    = _g("name", "Unknown")
    today   = _date.today().strftime("%d %b %Y")
    val     = llm_result.get("validation", {})
    nar     = llm_result.get("narrative", {})
    summary = val.get("summary", {})
    secs    = nar.get("report_sections", {})

    def _h(s: Any) -> str:
        return html_lib.escape(str(s or ""))

    band   = summary.get("confidence_band", "NEEDS_WORK")
    n_act  = summary.get("n_actual", 0)
    n_dir  = summary.get("n_direct", 0)
    n_near = summary.get("n_near", 0)
    n_miss = summary.get("n_miss", 0)

    rows = []
    for em in val.get("event_matches", []):
        mt   = em.get("match_type", "MISS")
        sigs = " ".join(f'<span class="tag">{_h(s)}</span>' for s in em.get("active_signals", [])[:5])
        mr   = (f'<br><span style="color:var(--danger);font-size:11px">{_h(em.get("miss_reason",""))}</span>'
                if mt == "MISS" and em.get("miss_reason") else "")
        rows.append(
            f"<tr><td>{em.get('actual_event_index','')}</td>"
            f"<td><b>{_h(em.get('actual_date',''))}</b><br>{_h(em.get('actual_description',''))}</td>"
            f"<td><span class='badge badge-{mt}'>{mt.replace('_',' ')}</span></td>"
            f"<td style='font-size:12px'>{_h(em.get('matched_block_md','?'))}/{_h(em.get('matched_block_ad','?'))}"
            f"<br>{_h(em.get('matched_block_start','?'))}&rarr;{_h(em.get('matched_block_end','?'))}</td>"
            f"<td style='font-size:12px'>{_h(em.get('predicted_event_type',''))}</td>"
            f"<td>{em.get('predicted_career_score',0):.2f}</td>"
            f"<td>{em.get('offset_months',0):+.1f} mo</td>"
            f"<td style='font-size:11px'>{sigs}{mr}</td></tr>"
        )
    event_rows = "\n".join(rows)

    _today_str    = _date.today().isoformat()
    _grace_cutoff = (_date.today() - _td(days=180)).isoformat()
    pm_past, pm_recent, pm_future = [], [], []
    for pm in val.get("predicted_misses", []):
        _end = pm.get("block_end", "") or ""
        if not _end or _end[:10] >= _today_str:
            pm_future.append(pm)
        elif _end[:10] >= _grace_cutoff:
            pm_recent.append(pm)
        else:
            pm_past.append(pm)

    def _pm_table(rows_data: list, title: str) -> str:
        if not rows_data:
            return ""
        _trows = []
        for pm in rows_data:
            sf = " ".join(f'<span class="tag">{_h(s)}</span>' for s in pm.get("suppression_factors", [])[:4])
            _trows.append(
                f"<tr><td>{_h(pm.get('block_md','?'))}/{_h(pm.get('block_ad','?'))}</td>"
                f"<td>{_h(pm.get('block_start','?'))}&rarr;{_h(pm.get('block_end','?'))}</td>"
                f"<td>{_h(pm.get('predicted_event_type',''))}</td>"
                f"<td>{pm.get('predicted_career_score',0):.2f}</td>"
                f"<td>{_h(pm.get('non_manifestation_hypothesis',''))}</td>"
                f"<td style='font-size:11px'>{sf}</td></tr>"
            )
        return (
            f"<h2>{title}</h2><table class='events-table'><thead><tr>"
            "<th>MD/AD</th><th>Period</th><th>Pred Type</th><th>Score</th>"
            "<th>Hypothesis</th><th>Suppression</th>"
            "</tr></thead><tbody>" + "\n".join(_trows) + "</tbody></table>"
        )

    predicted_misses_html = (
        _pm_table(pm_past,   "Predicted-But-Not-Manifested (Confirmed Past)")
        + _pm_table(pm_recent, "Recently Closed Windows &mdash; Outcome Unconfirmed (&lt; 6 months)")
        + _pm_table(pm_future, "Upcoming Forecast Windows (Not Yet Due)")
    ) or ""

    eg_blocks = val.get("engine_gaps", [])
    if eg_blocks:
        eg_rows = []
        for eg in eg_blocks:
            spu = " ".join(f'<span class="tag">{_h(s)}</span>'
                           for s in eg.get("signals_present_but_unscored", [])[:4])
            sc      = eg.get("engine_score_for_period")
            sc_str  = f"{sc:.2f}" if sc is not None else "&mdash;"
            _md     = eg.get("active_dasha_md") or "?"
            _ad     = eg.get("active_dasha_ad") or "?"
            _dasha  = f"{_h(_md)}/{_h(_ad)}"
            if _md in ("?", "not available") or _ad in ("?", "not available"):
                _dasha += '<br><span style="font-size:10px;color:var(--muted)">Dasha not in payload</span>'
            _sc_cell = (
                f'{sc_str}<br><span style="font-size:10px;color:var(--muted)">No timeline block for date</span>'
                if sc is None else sc_str
            )
            eg_rows.append(
                f"<tr><td>A{eg.get('actual_event_index','?'):02d}</td>"
                f"<td><b>{_h(eg.get('actual_date',''))}</b><br>{_h(eg.get('actual_description',''))}</td>"
                f"<td style='font-size:12px'>{_dasha}</td>"
                f"<td style='font-size:12px'>{_sc_cell}</td>"
                f"<td style='font-size:11px;color:var(--warn)'>{_h(eg.get('root_cause',''))}</td>"
                f"<td style='font-size:11px'>{spu}</td>"
                f"<td style='font-size:11px'>{_h(eg.get('recommended_fix',''))}</td></tr>"
            )
        engine_gaps_html = (
            "<h2>Engine Gaps &mdash; Actual Events Not Predicted</h2>"
            "<table class='events-table'><thead><tr>"
            "<th>#</th><th>Actual Event</th><th>Active Dasha</th><th>Engine Score</th>"
            "<th>Root Cause</th><th>Missed Signals</th><th>Recommended Fix</th>"
            "</tr></thead><tbody>" + "\n".join(eg_rows) + "</tbody></table>"
        )
    else:
        engine_gaps_html = ""

    sorted_factors = sorted(val.get("factor_attribution", []),
                            key=lambda x: x.get("importance_score", 0), reverse=True)
    if not sorted_factors:
        _kw: Dict[str, Any] = {
            "KP_CUSP_SUBLORD": (0.08, "KP sub-lord of H10/H6"),
            "G21_VIMSOPAKA":   (0.04, "Vimsopaka Bala"),
            "G18_D10_FULL":    (0.02, "D10 Dasamsha full scoring"),
            "G1_DIGBALA":      (0.06, "Directional strength"),
            "G7_ASHTAKA":      (0.05, "Ashtakavarga bindhu"),
            "G14_YOGA_BOOST":  (0.06, "Raj/Dhana yoga multiplier"),
            "G27_TRANSIT_ARC": (0.07, "Transit arc alignment"),
            "G33_MACRO_INDEX": (0.05, "Macro-economic index"),
        }
        for ir in val.get("engine_improvements", []):
            _kw[ir.get("factor_group", "")] = (float(ir.get("current_weight") or 0),
                                               ir.get("observed_pattern", ""))
        sorted_factors = [{"factor_id": fid, "importance_score": w, "hit_count": 0, "note": desc}
                          for fid, (w, desc) in _kw.items()]
    _mx = max((fa.get("importance_score", 0) for fa in sorted_factors[:24]), default=0.01) or 0.01
    cards = []
    for fa in sorted_factors[:24]:
        imp  = fa.get("importance_score", 0)
        bar  = max(6, int(imp / _mx * 85))
        hits = fa.get("hit_count", 0)
        col  = "#3fb950" if hits > 0 else ("#e3b341" if imp >= _mx * 0.6 else "#8b949e")
        cards.append(
            f"<div class='factor-card'>"
            f"<div class='factor-name'>{_h(fa.get('factor_id',''))}</div>"
            f"<div class='factor-bar-bg'><div class='factor-bar' "
            f"style='width:{bar}%;background:{col}'></div></div>"
            f"<div class='factor-meta'>weight={imp:.2f} &nbsp; hits={hits}</div>"
            f"<div style='font-size:11px;color:var(--muted);margin-top:4px'>"
            f"{_h(fa.get('note',''))}</div></div>"
        )
    factor_cards = "\n".join(cards)

    items = []
    for ir in sorted(val.get("engine_improvements", []), key=lambda x: x.get("priority", 99)):
        cw = ir.get("current_weight")
        cw_str = f" (current weight: {cw})" if cw is not None else ""
        items.append(
            f"<li><div class='pri'>Priority {ir.get('priority','')} &nbsp; Factor: "
            f"<span class='factor'>{_h(ir.get('factor_group',''))}</span>{_h(cw_str)}</div>"
            f"<div style='font-size:12px;margin:4px 0'><b>Pattern:</b> "
            f"{_h(ir.get('observed_pattern',''))}</div>"
            f"<div style='font-size:12px'><b>Action:</b> "
            f"{_h(ir.get('recommended_action',''))}</div></li>"
        )
    improve_items = "\n".join(items)

    flags = val.get("data_quality_flags", [])
    _FLAG_MAP = [
        ("dasha",      "flag-critical", "Blocks retroactive timeline scoring"),
        ("d10 lagna",  "flag-high",     "D10 ascendant missing &mdash; career chart degraded"),
        ("d10 house",  "flag-high",     "D10 house lords missing"),
        ("d10",        "flag-high",     "D10 divisional data missing"),
        ("moon naksh", "flag-high",     "Moon Nakshatra missing &mdash; KP sub-lord degraded"),
        ("nakshatra",  "flag-high",     "Nakshatra data missing"),
        ("arudha",     "flag-medium",   "Arudha Lagna missing"),
        ("karma pada", "flag-medium",   "Karma Pada (A10) missing"),
        ("yoga",       "flag-medium",   "Active Yogas not available"),
        ("lagna",      "flag-medium",   "Lagna detail missing"),
    ]

    def _flag_cls_impact(flag_text: str):
        fl = flag_text.lower()
        for substr, cls, impact in _FLAG_MAP:
            if substr in fl:
                return cls, impact
        return "flag-medium", "Reduces overall scoring accuracy"

    if flags:
        _fi = []
        for f in flags:
            _cls, _impact = _flag_cls_impact(f)
            _icon = "&#x1F534;" if "critical" in _cls else ("&#x1F7E1;" if "high" in _cls else "&#x1F535;")
            _fi.append(
                f"<div class='dq-flag {_cls}'><span class='dq-icon'>{_icon}</span>"
                f"<div><div class='dq-text'>{_h(f)}</div>"
                f"<div class='dq-impact'>{_impact}</div></div></div>"
            )
        data_flags_html = (
            f"<h2>Data Quality Flags</h2>"
            f"<div class='data-flags-grid'>{''.join(_fi)}</div>"
        )
    else:
        data_flags_html = ""

    _has_dasha_gap = any("dasha" in f.lower() and "not" in f.lower() for f in flags) or any(
        (eg.get("root_cause") or "").upper() in ("INSUFFICIENT_DATA", "MISSING_DASHA")
        for eg in val.get("engine_gaps", [])
    )
    retro_gap_html = (
        '<div style="background:rgba(248,81,73,.10);border:2px solid rgba(248,81,73,.5);'
        'border-radius:8px;padding:16px 20px;margin-bottom:20px;">'
        '<div style="font-size:15px;font-weight:700;color:#f85149;margin-bottom:6px;">'
        '&#x26A0; Retroactive Coverage Gap Detected</div>'
        '<div style="font-size:13px;color:var(--text);line-height:1.65">'
        'Actual career events predate the dasha sequence available to the engine. '
        'This is a <em>data gap</em>, not an engine failure.</div>'
        '<div style="font-size:12px;color:var(--muted);margin-top:8px;">'
        '<b>Fix:</b> Provide the full Vimshottari Dasha sequence from at least 2015 '
        'in the <code>dasha_periods</code> field.</div></div>'
    ) if _has_dasha_gap else ""

    _FLAG_FIX_MAP = {
        "dasha":      ("Critical", "Provide full Vimshottari Dasha sequence from 2015&ndash;2035",
                       "dasha_periods[]", "Unlocks retroactive scoring; MD_AD_STRENGTH becomes active"),
        "d10 lagna":  ("Critical", "Supply D10 ascendant sign", "d10.lagna",
                       "Enables career chart lord ID; impacts G5, G9, G16"),
        "d10 house":  ("Critical", "Supply D10 house lord assignments", "d10.house_lords{}",
                       "Required for H10/H6 signification checks"),
        "moon naksh": ("High", "Provide Moon Nakshatra", "moon_nakshatra",
                       "Enables KP sub-lord analysis and G21 Vimsopaka Bala"),
        "nakshatra":  ("High", "Provide planet nakshatra placements", "planet_nakshatras{}",
                       "Enables KP sub-lord analysis"),
        "arudha":     ("Medium", "Provide Arudha Lagna sign", "arudha_lagna",
                       "Enables Jaimini career manifestation checks"),
        "karma pada": ("Medium", "Provide Karma Pada (A10) sign", "karma_pada",
                       "Career reputation timing &mdash; A10 transit detection"),
        "yoga":       ("Medium", "Provide list of active natal yogas", "natal_yogas[]",
                       "Yoga activation bonuses currently contribute 0"),
    }
    _plan_items_html = []
    _plan_step = 1
    _seen_keys: set = set()
    for f in flags:
        fl = f.lower()
        for key, (sev, action, field, effect) in _FLAG_FIX_MAP.items():
            if key in fl and key not in _seen_keys:
                _seen_keys.add(key)
                _sc = ("plan-critical" if sev == "Critical"
                       else ("plan-high" if sev == "High" else "plan-medium"))
                _plan_items_html.append(
                    f"<div class='plan-item {_sc}'>"
                    f"<div class='plan-step'>Step {_plan_step} &nbsp;&middot;&nbsp; "
                    f"{sev} Priority &nbsp;&middot;&nbsp; Data Gap</div>"
                    f"<div class='plan-action'>{_h(action)}</div>"
                    f"<div style='margin:4px 0'><span class='plan-field'>{_h(field)}</span></div>"
                    f"<div class='plan-effect'>Effect: {_h(effect)}</div></div>"
                )
                _plan_step += 1
                break
    for ir in sorted(val.get("engine_improvements", []), key=lambda x: x.get("priority", 99)):
        _act = ir.get("recommended_action", "") or ""
        if not _act or ("ensure" in _act.lower() and "data" in _act.lower()):
            continue
        _cw = ir.get("current_weight")
        _plan_items_html.append(
            f"<div class='plan-item plan-medium'>"
            f"<div class='plan-step'>Step {_plan_step} &nbsp;&middot;&nbsp; Calibration &nbsp;&middot;&nbsp; "
            f"Factor: <span style='color:var(--accent);font-weight:600'>"
            f"{_h(ir.get('factor_group',''))}</span>"
            f"{_h(f' (weight: {_cw})' if _cw is not None else '')}</div>"
            f"<div class='plan-action'>{_h(_act)}</div>"
            f"<div class='plan-effect'>Pattern: {_h(ir.get('observed_pattern',''))}</div></div>"
        )
        _plan_step += 1
    computed_plan_html = "".join(_plan_items_html) if _plan_items_html else (
        "<div class='plan-item plan-medium'>"
        "<div class='plan-action'>No specific improvement actions identified.</div>"
        "<div class='plan-effect'>Engine has sufficient data for current chart.</div></div>"
    )

    html = _HTML_TEMPLATE.format(
        name=_h(name), today=today, version=VALIDATOR_VERSION,
        exec_summary=_h(nar.get("executive_summary", "No summary available.")),
        PAI_strict=summary.get("PAI_strict", 0),
        PAI_relaxed=summary.get("PAI_relaxed", 0),
        precision=summary.get("precision", 0),
        recall=summary.get("recall", 0),
        f1=summary.get("f1_score", 0),
        timing=summary.get("timing_accuracy_months", 0),
        n_direct=n_dir, n_actual=n_act, n_near=n_near, n_miss=n_miss, band=band,
        event_rows=event_rows,
        predicted_misses_html=predicted_misses_html,
        engine_gaps_html=engine_gaps_html,
        factor_cards=factor_cards,
        improve_items=improve_items,
        sec_overall=_h(secs.get("overall_assessment", "")),
        sec_period=_h(secs.get("period_analysis", "")),
        sec_factors=_h(secs.get("factor_insights", "")),
        computed_plan_html=computed_plan_html,
        data_flags_html=data_flags_html,
        retro_gap_html=retro_gap_html,
    )

    os.makedirs(output_dir, exist_ok=True)
    safe_name = "".join(c if c.isalnum() or c in "._-" else "_" for c in name)
    out_path  = os.path.join(output_dir, f"{safe_name}_career_validation.html")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(html)
    logger.info("[Validation] HTML report written: %s", out_path)
    return out_path


def parse_validation_response(raw_json: str) -> Dict:
    """Parse a raw Step 1 JSON string into a dict. Raises ValueError on failure."""
    try:
        result = json.loads(raw_json)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON from validator LLM: {exc}") from exc
    required_keys = {
        "validator_version", "summary", "event_matches",
        "predicted_misses", "engine_gaps", "factor_attribution",
        "engine_improvements", "data_quality_flags",
    }
    missing = required_keys - set(result.keys())
    if missing:
        raise ValueError(f"Validator response missing required keys: {missing}")
    return result


if __name__ == "__main__":
    import argparse, sys, os as _os
    import pathlib as _pathlib, re as _re
    _env_path = _pathlib.Path(__file__).parent.parent / ".env"
    if _env_path.exists():
        _env_re = _re.compile(r'^\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(["\']?)(.*?)\2\s*(?:#.*)?$')
        for _line in _env_path.read_text(encoding="utf-8").splitlines():
            _m = _env_re.match(_line)
            if _m:
                _k, _, _v = _m.groups()
                if _k not in _os.environ:
                    _os.environ[_k] = _v

    ap = argparse.ArgumentParser(description="JyotishAI Career Validator")
    ap.add_argument("chart",       help="Path to chart JSON")
    ap.add_argument("--history",   required=True, help="Path to actual career history JSON")
    ap.add_argument("--timeline",  required=True, help="Path to engine career timeline JSON")
    ap.add_argument("--out",       default="validation_reports", help="Output directory")
    ap.add_argument("--model",     default="gpt-5.4-mini", help="OpenAI model")
    ap.add_argument("--threshold", type=float, default=0.55, help="Career score threshold")
    args = ap.parse_args()

    with open(args.chart,    encoding="utf-8") as f: chart_data     = json.load(f)
    with open(args.history,  encoding="utf-8") as f: actual_history = json.load(f)
    with open(args.timeline, encoding="utf-8") as f: timeline_data  = json.load(f)

    predicted_blocks = (timeline_data.get("blocks", timeline_data.get("timeline", []))
                        if isinstance(timeline_data, dict) else timeline_data)

    print(f"\n[Career Validator] Chart: {chart_data.get('name', 'Unknown')}")
    print(f"  Actual events:    {len(actual_history)}")
    print(f"  Predicted blocks: {len(predicted_blocks)}")

    if not _os.environ.get("OPENAI_API_KEY"):
        print("[No OPENAI_API_KEY] Dry-run mode.\n")
        user_msg = build_validator_user_message(
            build_chart_summary_for_validation(chart_data),
            predicted_blocks, actual_history, score_threshold=args.threshold,
        )
        print(_VALIDATOR_SYSTEM_PROMPT[:2000] + "\n... [truncated]")
        print(user_msg[:3000] + ("\n... [truncated]" if len(user_msg) > 3000 else ""))
        sys.exit(0)

    result    = call_validation_llm(
        payload=chart_data, predicted_blocks=predicted_blocks,
        actual_history=actual_history, score_threshold=args.threshold, model=args.model,
    )
    html_path = generate_validation_html(result, chart_data, output_dir=args.out)
    print(f"\n✓ Validation HTML report: {html_path}")

    s = result["validation"].get("summary", {})
    print("\n━━━ RESULTS ━━━")
    print(f"  PAI strict:  {s.get('PAI_strict', 0):.2%}")
    print(f"  PAI relaxed: {s.get('PAI_relaxed', 0):.2%}")
    print(f"  F1 score:    {s.get('f1_score', 0):.2%}")
    print(f"  Timing acc.: {s.get('timing_accuracy_months', 0):.1f} months")
    print(f"  Band:        {s.get('confidence_band', 'N/A')}")
    print(f"  Verdict:     {s.get('one_line_verdict', '')}")

    import os as _os2
    _os2.makedirs(args.out, exist_ok=True)
    debug_path = _os2.path.join(args.out, "validation_debug.json")
    with open(debug_path, "w", encoding="utf-8") as fh:
        json.dump(result, fh, indent=2, ensure_ascii=False, default=str)
    print(f"  Debug JSON:  {debug_path}")
