"""Strict registry/affinity/ontology coverage validation for JyotishAI.

Drop this file at: jyotish/registry_coverage_validator.py

Use in tests:
    from jyotish.registry_coverage_validator import validate_all_coverage
    validate_all_coverage(fail_fast=True)

Use from CLI:
    python -m jyotish.registry_coverage_validator --registry jyotish/india_course_registry_v12.json
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Set


class RegistryCoverageError(RuntimeError):
    pass


# Generated by registry_loader_v12 from fully validated parent records.
GENERATED_REGISTRY_IDS = {
    "operations_research", "information_systems", "it_systems_planning",
    "software_infrastructure_engineering", "engineering_management", "it_business_advisory",
    "it_governance",
}


def _load_registry_ids(registry_path: str | Path) -> Set[str]:
    data = json.loads(Path(registry_path).read_text(encoding="utf-8"))
    branches = data.get("branches", {}) or {}
    if not branches:
        raise RegistryCoverageError(f"Registry is empty: {registry_path}")
    return set(branches)


def _load_registry(registry_path: str | Path) -> Dict[str, Any]:
    data = json.loads(Path(registry_path).read_text(encoding="utf-8"))
    branches = data.get("branches", {}) or {}
    if not branches:
        raise RegistryCoverageError(f"Registry is empty: {registry_path}")
    return branches


def coverage_report(registry_path: str | Path, check_v12_schema: bool = True) -> Dict[str, Any]:
    """
    §4 remediation (2026-08-19): `check_v12_schema` lets the caller run the
    registry/affinity/ontology ID-orphan check (the actual "does every
    registry field id have a matching affinity-vector id and vice versa"
    requirement §4 mandates run before EVERY scoring run) against a v11
    fallback registry too, WITHOUT also enforcing the `required_v12`
    section-completeness check below, which is genuinely v12-only schema
    (a legitimate v11 file lacks those sections by design, not by error).
    Previously the whole validator was skipped entirely for a v11 fallback
    (see registry_loader_v12.py's old `path.name.endswith("v12.json")`
    gate) -- so orphaned ids on either side could silently reach a scoring
    run whenever v12 was missing/corrupted. Splitting the two concerns lets
    the orphan-id check run unconditionally while the v12-schema-shape
    check still only applies when the loaded file actually claims to be v12.
    """
    from jyotish.affinity import BRANCH_PLANET_AFFINITY
    from Field_Determination.competency_ontology import FIELD_TO_FAMILY, FAMILY_META, COMPETENCY_META

    registry = _load_registry(registry_path)
    registry_ids = set(registry) | GENERATED_REGISTRY_IDS
    affinity_ids = set(BRANCH_PLANET_AFFINITY)
    ontology_ids = set(FIELD_TO_FAMILY)
    errors: List[str] = []

    def diff(name_a: str, a: Set[str], name_b: str, b: Set[str]) -> Dict[str, List[str]]:
        return {
            f"{name_a}_not_in_{name_b}": sorted(a - b),
            f"{name_b}_not_in_{name_a}": sorted(b - a),
        }

    d_reg_aff = diff("registry", registry_ids, "affinity", affinity_ids)
    d_reg_onto = diff("registry", registry_ids, "ontology", ontology_ids)
    d_onto_aff = diff("ontology", ontology_ids, "affinity", affinity_ids)

    for label, values in {**d_reg_aff, **d_reg_onto, **d_onto_aff}.items():
        if values:
            errors.append(f"{label}: {len(values)}")

    invalid_families = sorted({fam for fam in FIELD_TO_FAMILY.values() if fam not in FAMILY_META})
    invalid_competencies = sorted({meta.get("competency") for meta in FAMILY_META.values() if meta.get("competency") not in COMPETENCY_META})
    if invalid_families:
        errors.append(f"invalid family ids: {invalid_families}")
    if invalid_competencies:
        errors.append(f"invalid competency ids: {invalid_competencies}")

    schema_missing: Dict[str, List[str]] = {}
    ontology_family_drift: Dict[str, Dict[str, str]] = {}
    if check_v12_schema:
        required_v12 = {"classic_core", "modern_extensions", "ontology", "education_realism", "curriculum", "market", "risk", "routes", "career_outcomes"}
        for fid, branch in registry.items():
            missing = sorted(required_v12 - set(branch))
            if missing:
                schema_missing[fid] = missing
        if schema_missing:
            errors.append(f"branches missing v12 sections: {len(schema_missing)}")

        # Value-level drift check: id-set membership above can pass while the
        # JSON's embedded ontology.primary_family/primary_competency silently
        # disagrees with the runtime FIELD_TO_FAMILY assignment for the same
        # field -- the same dual-source-of-truth failure mode that previously
        # affected planet_affinity, recurring in miniature for ontology family.
        for fid, branch in registry.items():
            runtime_family = FIELD_TO_FAMILY.get(fid)
            if runtime_family is None:
                continue
            json_onto = branch.get("ontology") or {}
            json_family = json_onto.get("primary_family")
            if json_family != runtime_family:
                ontology_family_drift[fid] = {
                    "registry_primary_family": json_family,
                    "runtime_primary_family": runtime_family,
                }
                continue
            # Family ids agree; also check competency, since a field can be
            # remapped to a family under a different competency bucket than the
            # JSON's cached primary_competency (e.g. behavioural_social vs.
            # computational_intelligence for the same family swap).
            runtime_competency = FAMILY_META.get(runtime_family, {}).get("competency")
            json_competency = json_onto.get("primary_competency")
            if runtime_competency is not None and json_competency != runtime_competency:
                ontology_family_drift[fid] = {
                    "registry_primary_competency": json_competency,
                    "runtime_primary_competency": runtime_competency,
                }
        if ontology_family_drift:
            errors.append(f"ontology family/competency drift: {len(ontology_family_drift)}")

    return {
        "ok": not errors,
        "errors": errors,
        "counts": {
            "registry": len(registry_ids),
            "affinity": len(affinity_ids),
            "ontology": len(ontology_ids),
        },
        "diffs": {
            **d_reg_aff,
            **d_reg_onto,
            **d_onto_aff,
            "invalid_families": invalid_families,
            "invalid_competencies": invalid_competencies,
            "schema_missing": schema_missing,
            "ontology_family_drift": ontology_family_drift,
        },
    }


def validate_all_coverage(
    registry_path: str | Path = None,
    fail_fast: bool = True,
    check_v12_schema: bool | None = None,
) -> Dict[str, Any]:
    if registry_path is None:
        registry_path = Path(__file__).with_name("india_course_registry_v12.json")
        if not Path(registry_path).exists():
            registry_path = Path(__file__).with_name("india_course_registry_v11.json")
    # §4 remediation (2026-08-19): default check_v12_schema from the actual
    # filename when the caller doesn't specify -- so a caller that always
    # invokes this function (see registry_loader_v12.py, now unconditional)
    # still only enforces the v12-only schema-section check against a real
    # v12 file, never against a legitimate v11 fallback.
    if check_v12_schema is None:
        check_v12_schema = str(registry_path).endswith("v12.json")
    report = coverage_report(registry_path, check_v12_schema=check_v12_schema)
    if fail_fast and not report["ok"]:
        raise RegistryCoverageError(json.dumps(report, indent=2, ensure_ascii=False))
    return report


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--registry", default=str(Path(__file__).with_name("india_course_registry_v12.json")))
    p.add_argument("--no-fail", action="store_true")
    args = p.parse_args()
    report = validate_all_coverage(args.registry, fail_fast=not args.no_fail)
    print(json.dumps(report, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
